labelingsystem-server: AuthResource Class Reference
AuthResource Class Reference
Public Member Functions
Response loginUser (@FormParam("user") String user, @FormParam("pwd") String pwd)
Response statusUser (@QueryParam("user") String user, @QueryParam("token") String token)
Response logoutUser (@FormParam("user") String user)
Response getHash (@QueryParam("str") String str)
Member Function Documentation
getHash()
Response getHash (@QueryParam("str") String str)
{
         try {
             String salt = Crypt.generateHash();
             String hash = salt + Crypt.SHA1(salt + str);
             JSONObject jsonOut = new JSONObject();
             jsonOut.put("hash", hash);
             return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
         } catch (Exception e) {
             return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.AuthResource"))
                     .header("Content-Type", "application/json;charset=UTF-8").build();
         }
     }
References Crypt.generateHash(), Logging.getMessageJSON(), and Crypt.SHA1().
loginUser()
Response loginUser (@FormParam("user") String user, @FormParam("pwd") String pwd)
{
         JSONObject jsonOut = new JSONObject();
         JSONObject jsonStatus = new JSONObject();
         JSONObject jsonUser = new JSONObject();
         try {
             String secretToken = UniqueIdentifier.getHashID();
             String role = SQlite.getUserInfoAndCheckPassword(user, pwd);
             boolean login = SQlite.setLogin(user + ";" + secretToken, role);
             if (login) {
                 String status[] = SQlite.getLoginStatus(user + ";" + secretToken);
                 jsonStatus.put("verified", true);
                 jsonStatus.put("user", user);
                 jsonStatus.put("role", status[0]);
                 jsonStatus.put("date", status[1]);
                 jsonStatus.put("token", secretToken);
                 jsonOut.put("status", jsonStatus);
                 // get agent object
                 RDF rdf = new RDF();
                 String item = "ls_age";
                 String query = GeneralFunctions.getAllElementsForItemID(item, user);
                 List<BindingSet> result = RDF4J_20.SPARQLquery(ConfigProperties.getPropertyParam("repository"), ConfigProperties.getPropertyParam("ts_server"), query);
                 List<String> predicates = RDF4J_20.getValuesFromBindingSet_ORDEREDLIST(result, "p");
                 List<String> objects = RDF4J_20.getValuesFromBindingSet_ORDEREDLIST(result, "o");
                 if (result.size() > 0) {
                     for (int i = 0; i < predicates.size(); i++) {
                         rdf.setModelTriple(item + ":" + user, predicates.get(i), objects.get(i));
                     }
                     String jsonObject = Transformer.agent_GET(rdf.getModel("RDF/JSON"), user).toJSONString();
                     jsonUser = (JSONObject) new JSONParser().parse(jsonObject);
                     jsonOut.put("user", jsonUser);
                 }
             }
             return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
         } catch (Exception e) {
             if (e.toString().contains("AccessDeniedException")) {
                 return Response.status(Response.Status.FORBIDDEN).entity(Logging.getMessageJSON(e, "v1.rest.AuthResource"))
                         .header("Content-Type", "application/json;charset=UTF-8").build();
             } else {
                 return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.AuthResource"))
                         .header("Content-Type", "application/json;charset=UTF-8").build();
             }
         }
     }
References Transformer.agent_GET(), GeneralFunctions.getAllElementsForItemID(), UniqueIdentifier.getHashID(), SQlite.getLoginStatus(), Logging.getMessageJSON(), ConfigProperties.getPropertyParam(), SQlite.getUserInfoAndCheckPassword(), and SQlite.setLogin().
logoutUser()
Response logoutUser (@FormParam("user") String user)
{
         JSONObject jsonOut = new JSONObject();
         try {
             boolean logout = SQlite.setLogout(user);
             if (logout) {
                 jsonOut.put("verified", false);
                 jsonOut.put("user", user);
             }
             return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
         } catch (Exception e) {
             return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.AuthResource"))
                     .header("Content-Type", "application/json;charset=UTF-8").build();
         }
     }
References Logging.getMessageJSON(), and SQlite.setLogout().
statusUser()
Response statusUser (@QueryParam("user") String user, @QueryParam("token") String token)
{
         JSONObject jsonOut = new JSONObject();
         JSONObject jsonStatus = new JSONObject();
         JSONObject jsonUser = new JSONObject();
         try {
             String status[] = SQlite.getLoginStatus(user + ";" + token);
             if (status[0] != null) {
                 jsonStatus.put("verified", true);
                 jsonStatus.put("user", user);
                 jsonStatus.put("role", status[0]);
                 jsonStatus.put("date", status[1]);
                 jsonOut.put("status", jsonStatus);
                 // get agent object
                 RDF rdf = new RDF();
                 String item = "ls_age";
                 String query = GeneralFunctions.getAllElementsForItemID(item, user);
                 List<BindingSet> result = RDF4J_20.SPARQLquery(ConfigProperties.getPropertyParam("repository"), ConfigProperties.getPropertyParam("ts_server"), query);
                 List<String> predicates = RDF4J_20.getValuesFromBindingSet_ORDEREDLIST(result, "p");
                 List<String> objects = RDF4J_20.getValuesFromBindingSet_ORDEREDLIST(result, "o");
                 if (result.size() > 0) {
                     for (int i = 0; i < predicates.size(); i++) {
                         rdf.setModelTriple(item + ":" + user, predicates.get(i), objects.get(i));
                     }
                     String jsonObject = Transformer.agent_GET(rdf.getModel("RDF/JSON"), user).toJSONString();
                     jsonUser = (JSONObject) new JSONParser().parse(jsonObject);
                     jsonOut.put("user", jsonUser);
                 }
             } else {
                 jsonOut.put("verified", false);
                 jsonOut.put("user", user);
                 throw new AccessDeniedException();
             }
             return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
         } catch (Exception e) {
             if (e.toString().contains("AccessDeniedException")) {
                 return Response.status(Response.Status.FORBIDDEN).entity(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
             } else {
                 return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.AuthResource"))
                         .header("Content-Type", "application/json;charset=UTF-8").build();
             }
         }
     }
References Transformer.agent_GET(), GeneralFunctions.getAllElementsForItemID(), SQlite.getLoginStatus(), Logging.getMessageJSON(), and ConfigProperties.getPropertyParam().