labelingsystem-server: RDF Class Reference
RDF Class Reference
CLASS for set up a RDF graph and export it.
Public Member Functions
RDF () throws IOException
Model getModelObject ()
String getPrefixItem (String shortDesc)
String getPREFIXSPARQL ()
void setModelLiteral (String subject, String predicate, String object) throws RdfException
void setModelLiteralLanguage (String subject, String predicate, String object, String lang) throws RdfException
void setModelURI (String subject, String predicate, String object) throws RdfException
void setModelTriple (String subject, String predicate, String object) throws RdfException
String getModel () throws RdfException
String getModel (String format) throws UnsupportedEncodingException, RdfException
Private Attributes
Model model = null
final String PREFIX_LABELINGSYSTEM = "http://labeling.link/docs/ls/core#"
final String PREFIX_SKOS = "http://www.w3.org/2004/02/skos/core#"
final String PREFIX_DCTERMS = "http://purl.org/dc/terms/"
final String PREFIX_DCELEMENTS = "http://purl.org/dc/elements/1.1/"
final String PREFIX_RDFS = "http://www.w3.org/2000/01/rdf-schema#"
final String PREFIX_OWL = "http://www.w3.org/2002/07/owl#"
final String PREFIX_RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
final String PREFIX_FOAF = "http://xmlns.com/foaf/0.1/"
final String PREFIX_PROV = "http://www.w3.org/ns/prov#"
final String PREFIX_XSD = "http://www.w3.org/2001/XMLSchema#"
final String PREFIX_GEO = "http://www.w3.org/2003/01/geo/wgs84_pos#"
final String PREFIX_DCAT = "http://www.w3.org/ns/dcat#"
String Instance_VOCABULARY_ITEM = "http://$host/$item/$vocabulary/"
String Instance_LABEL_ITEM = "http://$host/$item/$label/"
String Instance_AGENT_ITEM = "http://$host/$item/$agent/"
String Instance_REVISION_ITEM = "http://$host/$item/$revision/"
String PREFIXSPARQL
Detailed Description
CLASS for set up a RDF graph and export it.
Author
Florian Thiery M.Sc.
i3mainz - Institute for Spatial Information and Surveying Technology
Version
27.06.2015
Constructor & Destructor Documentation
RDF()
RDF () throws IOException
References ConfigProperties.getPropertyParam().
{
         model = ModelFactory.createDefaultModel();
         model.setNsPrefix("ls", PREFIX_LABELINGSYSTEM);
         model.setNsPrefix("skos", PREFIX_SKOS);
         model.setNsPrefix("dct", PREFIX_DCTERMS);
         model.setNsPrefix("dc", PREFIX_DCELEMENTS);
         model.setNsPrefix("rdfs", PREFIX_RDFS);
         model.setNsPrefix("owl", PREFIX_OWL);
         model.setNsPrefix("rdf", PREFIX_RDF);
         model.setNsPrefix("foaf", PREFIX_FOAF);
         model.setNsPrefix("prov", PREFIX_PROV);
         model.setNsPrefix("xsd", PREFIX_XSD);
         model.setNsPrefix("geo", PREFIX_GEO);
         model.setNsPrefix("dcat", PREFIX_DCAT);
         Instance_VOCABULARY_ITEM = Instance_VOCABULARY_ITEM.replace("$host", ConfigProperties.getPropertyParam("host")).replace("$item", ConfigProperties.getPropertyParam("item")).replace("$vocabulary", ConfigProperties.getPropertyParam("vocabulary"));
         Instance_LABEL_ITEM = Instance_LABEL_ITEM.replace("$host", ConfigProperties.getPropertyParam("host")).replace("$item", ConfigProperties.getPropertyParam("item")).replace("$label", ConfigProperties.getPropertyParam("label"));
         Instance_AGENT_ITEM = Instance_AGENT_ITEM.replace("$host", ConfigProperties.getPropertyParam("host")).replace("$item", ConfigProperties.getPropertyParam("item")).replace("$agent", ConfigProperties.getPropertyParam("agent"));
         Instance_REVISION_ITEM = Instance_REVISION_ITEM.replace("$host", ConfigProperties.getPropertyParam("host")).replace("$item", ConfigProperties.getPropertyParam("item")).replace("$revision", ConfigProperties.getPropertyParam("revision"));
         PREFIXSPARQL = PREFIXSPARQL
                                 .replace("$host", ConfigProperties.getPropertyParam("host"))
                                 .replace("$item", ConfigProperties.getPropertyParam("item"))
                                 .replace("$vocabulary", ConfigProperties.getPropertyParam("vocabulary"))
                                 .replace("$label", ConfigProperties.getPropertyParam("label"))
                                 .replace("$agent", ConfigProperties.getPropertyParam("agent"))
                                 .replace("$revision", ConfigProperties.getPropertyParam("revision"));
     }
Member Function Documentation
getModel() [1/2]
String getModel () throws RdfException
Referenced by AgentsResource.getAgent(), AgentsResource.getAgent_JSON(), AgentsResource.getAgent_XML(), AgentsResource.getAgentRDF_JSONLD(), AgentsResource.getAgentRDF_JSONRDF(), AgentsResource.getAgentRDF_N3(), AgentsResource.getAgentRDF_Turtle(), AgentsResource.getAgentRDF_XML(), AgentsResource.getAgents(), LabelsResource.getLabel(), LabelsResource.getLabel_JSON(), LabelsResource.getLabel_XML(), LabelsResource.getLabelRDF_JSONLD(), LabelsResource.getLabelRDF_JSONRDF(), LabelsResource.getLabelRDF_N3(), LabelsResource.getLabelRDF_Turtle(), LabelsResource.getLabelRDF_XML(), LabelsResource.getLabels(), RevisionsResource.getRevision(), RevisionsResource.getRevision_JSON(), RevisionsResource.getRevision_XML(), RevisionsResource.getRevisionRDF_JSONLD(), RevisionsResource.getRevisionRDF_JSONRDF(), RevisionsResource.getRevisionRDF_N3(), RevisionsResource.getRevisionRDF_Turtle(), RevisionsResource.getRevisionRDF_XML(), RevisionsResource.getRevisions(), VocabsResource.getVocabularies(), VocabsResource.getVocabulary(), VocabsResource.getVocabulary_JSON(), VocabsResource.getVocabulary_XML(), VocabsResource.getVocabularyRDF_JSONLD(), VocabsResource.getVocabularyRDF_JSONRDF(), VocabsResource.getVocabularyRDF_N3(), VocabsResource.getVocabularyRDF_SKOS(), VocabsResource.getVocabularyRDF_Turtle(), VocabsResource.getVocabularyRDF_XML(), AuthResource.loginUser(), AgentsResource.postAgent(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), AuthResource.statusUser(), AgentsResource.updateAgent(), LabelsResource.updateLabel(), and VocabsResource.updateVocabulary().
{
         try {
             JenaJSONLD.init();
             ByteArrayOutputStream o = new ByteArrayOutputStream();
             model.write(o, "RDF/XML");
             model.removeAll();
             return o.toString("UTF-8");
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
getModel() [2/2]
String getModel (String format) throws UnsupportedEncodingException, RdfException
{
         // https://jena.apache.org/documentation/io/rdf-output.html#jena_model_write_formats
         try {
             JenaJSONLD.init();
             ByteArrayOutputStream o = new ByteArrayOutputStream();
             model.write(o, format);
             model.removeAll();
             return o.toString("UTF-8");
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
getModelObject()
Model getModelObject ()
References RDF.model.
{
         return model;
     }
getPrefixItem()
String getPrefixItem (String shortDesc)
Referenced by Transformer.agent_GET(), Transformer.agent_POST(), CSV.createLabelTriples(), VocabsResource.deleteLabelsSPARQLUPDATE(), AgentsResource.getAgents(), LabelsResource.getLabels(), RevisionsResource.getRevisions(), AutocompleteResource.getSuggestionsForLabelsFilter(), VocabsResource.getVocabularies(), Retcat_LabelingSystem.info(), Transformer.label_GET(), Transformer.label_POST(), Transformer.revision_GET(), RDF.setModelLiteral(), RDF.setModelLiteralLanguage(), RDF.setModelURI(), Transformer.vocabulary_GET(), Transformer.vocabulary_POST(), and Transformer.writeVocabularyStatisticsToDatabase().
{
         if (shortDesc.startsWith("ls:")) {
             return shortDesc.replace("ls:", PREFIX_LABELINGSYSTEM);
         } else if (shortDesc.startsWith("skos:")) {
             return shortDesc.replace("skos:", PREFIX_SKOS);
         } else if (shortDesc.startsWith("dct:")) {
             return shortDesc.replace("dct:", PREFIX_DCTERMS);
         } else if (shortDesc.startsWith("dc:")) {
             return shortDesc.replace("dc:", PREFIX_DCELEMENTS);
         } else if (shortDesc.startsWith("rdfs:")) {
             return shortDesc.replace("rdfs:", PREFIX_RDFS);
         } else if (shortDesc.startsWith("owl:")) {
             return shortDesc.replace("owl:", PREFIX_OWL);
         } else if (shortDesc.startsWith("rdf:")) {
             return shortDesc.replace("rdf:", PREFIX_RDF);
         } else if (shortDesc.startsWith("foaf:")) {
             return shortDesc.replace("foaf:", PREFIX_FOAF);
         } else if (shortDesc.startsWith("prov:")) {
             return shortDesc.replace("prov:", PREFIX_PROV);
         } else if (shortDesc.startsWith("xsd:")) {
             return shortDesc.replace("xsd:", PREFIX_XSD);
         } else if (shortDesc.startsWith("geo:")) {
             return shortDesc.replace("geo:", PREFIX_GEO);
         } else if (shortDesc.startsWith("dcat:")) {
             return shortDesc.replace("dcat:", PREFIX_DCAT);
         } else if (shortDesc.startsWith("ls_voc:")) {
             return shortDesc.replace("ls_voc:", Instance_VOCABULARY_ITEM);
         } else if (shortDesc.startsWith("ls_lab:")) {
             return shortDesc.replace("ls_lab:", Instance_LABEL_ITEM);
         } else if (shortDesc.startsWith("ls_age:")) {
             return shortDesc.replace("ls_age:", Instance_AGENT_ITEM);
         } else if (shortDesc.startsWith("ls_rev:")) {
             return shortDesc.replace("ls_rev:", Instance_REVISION_ITEM);
         } else {
             return shortDesc;
         }
     }
getPREFIXSPARQL()
String getPREFIXSPARQL ()
References RDF.PREFIXSPARQL.
Referenced by AgentsResource.createAgentSPARQLUPDATE(), LabelsResource.createLabelSPARQLUPDATE(), VocabsResource.createVocabularySPARQLUPDATE(), AgentsResource.deleteAgentSPARQLUPDATE(), VocabsResource.deleteItemsSPARQLUPDATE(), LabelsResource.deleteItemsSPARQLUPDATE(), LabelsResource.deleteLabel(), LabelsResource.deleteLabelSPARQLUPDATE(), VocabsResource.deleteLabelsSPARQLUPDATE(), VocabsResource.deleteVocabularySPARQLUPDATE(), AgentsResource.getAgents(), GeneralFunctions.getAllElementsForItemID(), GeneralFunctions.getAllLabelsForVocabulary(), InfoResource.getAPIpage(), GeneralFunctions.getHierarchyForLabelsOneStep(), LabelsResource.getInheritedFromVocabList(), LabelsResource.getLabels(), GeneralFunctions.getRelationsForLabelsByCreator(), RevisionsResource.getRevisions(), GeneralFunctions.getSPARQLqueryElementsForRetcatsItem(), AutocompleteResource.getSuggestionsForAgents(), AutocompleteResource.getSuggestionsForLabels(), AutocompleteResource.getSuggestionsForLabelsFilter(), AutocompleteResource.getSuggestionsForVocabs(), VocabsResource.getVocabularies(), TestsResource.initTest(), CSV.Input(), Transformer.label_GET(), VocabsResource.modifySPARQLUPDATE(), LabelsResource.modifySPARQLUPDATE(), AgentsResource.putAgentSPARQLUPDATE(), LabelsResource.revisionSPARQLUPDATE(), and LabelsResource.updateLabel().
{
         return PREFIXSPARQL;
     }
setModelLiteral()
void setModelLiteral (String subject, String predicate, String object) throws RdfException
References RDF.getPrefixItem().
Referenced by RDF.setModelTriple().
{
         try {
             Resource s = model.createResource(getPrefixItem(subject));
             Property p = model.createProperty(getPrefixItem(predicate));
             Literal o = model.createLiteral(object);
             model.add(s, p, o);
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
setModelLiteralLanguage()
void setModelLiteralLanguage (String subject, String predicate, String object, String lang) throws RdfException
References RDF.getPrefixItem().
Referenced by RDF.setModelTriple().
{
         try {
             Resource s = model.createResource(getPrefixItem(subject));
             Property p = model.createProperty(getPrefixItem(predicate));
             Literal o = model.createLiteral(object, lang);
             model.add(s, p, o);
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
setModelTriple()
void setModelTriple (String subject, String predicate, String object) throws RdfException
References RDF.setModelLiteral(), RDF.setModelLiteralLanguage(), and RDF.setModelURI().
Referenced by AgentsResource.getAgent(), AgentsResource.getAgent_JSON(), AgentsResource.getAgent_XML(), AgentsResource.getAgentRDF_JSONLD(), AgentsResource.getAgentRDF_JSONRDF(), AgentsResource.getAgentRDF_N3(), AgentsResource.getAgentRDF_Turtle(), AgentsResource.getAgentRDF_XML(), AgentsResource.getAgents(), LabelsResource.getLabel(), LabelsResource.getLabel_JSON(), LabelsResource.getLabel_XML(), LabelsResource.getLabelRDF_JSONLD(), LabelsResource.getLabelRDF_JSONRDF(), LabelsResource.getLabelRDF_N3(), LabelsResource.getLabelRDF_Turtle(), LabelsResource.getLabelRDF_XML(), LabelsResource.getLabels(), RevisionsResource.getRevision(), RevisionsResource.getRevision_JSON(), RevisionsResource.getRevision_XML(), RevisionsResource.getRevisionRDF_JSONLD(), RevisionsResource.getRevisionRDF_JSONRDF(), RevisionsResource.getRevisionRDF_N3(), RevisionsResource.getRevisionRDF_Turtle(), RevisionsResource.getRevisionRDF_XML(), RevisionsResource.getRevisions(), VocabsResource.getVocabularies(), VocabsResource.getVocabulary(), VocabsResource.getVocabulary_JSON(), VocabsResource.getVocabulary_XML(), VocabsResource.getVocabularyRDF_JSONLD(), VocabsResource.getVocabularyRDF_JSONRDF(), VocabsResource.getVocabularyRDF_N3(), VocabsResource.getVocabularyRDF_SKOS(), VocabsResource.getVocabularyRDF_Turtle(), VocabsResource.getVocabularyRDF_XML(), AuthResource.loginUser(), AgentsResource.postAgent(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), AuthResource.statusUser(), AgentsResource.updateAgent(), LabelsResource.updateLabel(), and VocabsResource.updateVocabulary().
{
         try {
             if (object.startsWith("http://") || object.contains("mailto")) {
                 setModelURI(subject, predicate, object);
             } else if (object.contains("@")) {
                 String literalLanguage[] = object.split("@");
                 setModelLiteralLanguage(subject, predicate, literalLanguage[0].replaceAll("\"", ""), literalLanguage[1]);
             } else {
                 setModelLiteral(subject, predicate, object.replaceAll("\"", ""));
             }
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
setModelURI()
void setModelURI (String subject, String predicate, String object) throws RdfException
References RDF.getPrefixItem().
Referenced by RDF.setModelTriple().
{
         try {
             Resource s = model.createResource(getPrefixItem(subject));
             Property p = model.createProperty(getPrefixItem(predicate));
             Resource o = model.createResource(getPrefixItem(object));
             model.add(s, p, o);
         } catch (Exception e) {
             throw new RdfException(e.getMessage());
         }
     }
Member Data Documentation
Instance_AGENT_ITEM
String Instance_AGENT_ITEM = "http://$host/$item/$agent/" private
Instance_LABEL_ITEM
String Instance_LABEL_ITEM = "http://$host/$item/$label/" private
Instance_REVISION_ITEM
String Instance_REVISION_ITEM = "http://$host/$item/$revision/" private
Instance_VOCABULARY_ITEM
String Instance_VOCABULARY_ITEM = "http://$host/$item/$vocabulary/" private
model
Model model = null private
Referenced by RDF.getModelObject().
PREFIX_DCAT
final String PREFIX_DCAT = "http://www.w3.org/ns/dcat#" private
PREFIX_DCELEMENTS
final String PREFIX_DCELEMENTS = "http://purl.org/dc/elements/1.1/" private
PREFIX_DCTERMS
final String PREFIX_DCTERMS = "http://purl.org/dc/terms/" private
PREFIX_FOAF
final String PREFIX_FOAF = "http://xmlns.com/foaf/0.1/" private
PREFIX_GEO
final String PREFIX_GEO = "http://www.w3.org/2003/01/geo/wgs84_pos#" private
PREFIX_LABELINGSYSTEM
final String PREFIX_LABELINGSYSTEM = "http://labeling.link/docs/ls/core#" private
PREFIX_OWL
final String PREFIX_OWL = "http://www.w3.org/2002/07/owl#" private
PREFIX_PROV
final String PREFIX_PROV = "http://www.w3.org/ns/prov#" private
PREFIX_RDF
final String PREFIX_RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#" private
PREFIX_RDFS
final String PREFIX_RDFS = "http://www.w3.org/2000/01/rdf-schema#" private
PREFIX_SKOS
final String PREFIX_SKOS = "http://www.w3.org/2004/02/skos/core#" private
PREFIX_XSD
final String PREFIX_XSD = "http://www.w3.org/2001/XMLSchema#" private
PREFIXSPARQL
String PREFIXSPARQL private
Initial value:
= ""
            + "PREFIX ls: <" + PREFIX_LABELINGSYSTEM + "> "
            + "PREFIX ls_voc: <" + Instance_VOCABULARY_ITEM + "> "
            + "PREFIX ls_lab: <" + Instance_LABEL_ITEM + "> "
            + "PREFIX ls_age: <" + Instance_AGENT_ITEM + "> "
            + "PREFIX ls_rev: <" + Instance_REVISION_ITEM + "> "
            + "PREFIX skos: <" + PREFIX_SKOS + "> "
            + "PREFIX rdf: <" + PREFIX_RDF + "> "
            + "PREFIX rdfs: <" + PREFIX_RDFS + "> "
            + "PREFIX dc: <" + PREFIX_DCELEMENTS + "> "
            + "PREFIX dct: <" + PREFIX_DCTERMS + "> "
            + "PREFIX owl: <" + PREFIX_OWL + "> "
            + "PREFIX xsd: <" + PREFIX_XSD + "> "
            + "PREFIX prov: <" + PREFIX_PROV + "> "
            + "PREFIX foaf: <" + PREFIX_FOAF + "> "
            + "PREFIX geo: <" + PREFIX_GEO + "> "
            + "PREFIX dcat: <" + PREFIX_DCAT + "> "
Referenced by RDF.getPREFIXSPARQL().