labelingsystem-server: Main Class Reference
Main Class Reference
Public Member Functions
String getServletInfo ()
Returns a short description of the servlet.
Protected Member Functions
void processRequest (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Handles the HTTP GET method.
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Handles the HTTP POST method.
Member Function Documentation
doGet()
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Handles the HTTP GET method.
Parameters
request servlet request
response servlet response
Exceptions
ServletException if a servlet-specific error occurs
IOException if an I/O error occurs
{
         processRequest(request, response);
     }
References Main.processRequest().
doPost()
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Handles the HTTP POST method.
Parameters
request servlet request
response servlet response
Exceptions
ServletException if a servlet-specific error occurs
IOException if an I/O error occurs
{
         processRequest(request, response);
     }
References Main.processRequest().
getServletInfo()
String getServletInfo ()
Returns a short description of the servlet.
Returns
a String containing servlet description
{
         return "Short description";
     }// </editor-fold>
processRequest()
void processRequest (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
{
         response.setContentType("application/json;charset=UTF-8");
         try (PrintWriter out = response.getWriter()) {
             JSONObject outObject = new JSONObject();
             outObject.put("title", "Labeling System API");
             JSONObject versionObject = new JSONObject();
             versionObject.put("1.0", ConfigProperties.getPropertyParam("api") + "/v1");
             outObject.put("versions", versionObject);
             // get last build data
             File file = new File(InfoResource.class.getClassLoader().getResource("configLabelingLink.properties").getFile());
             SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
             outObject.put("last build", sdf.format(file.lastModified()));
             out.print(outObject);
         } catch (Exception e) {
             response.sendError(500, e.toString());
         }
     }
References ConfigProperties.getPropertyParam().
Referenced by Main.doGet(), and Main.doPost().