labelingsystem-server: Logging Class Reference
Logging Class Reference
ERROR MESSAGE for catch exceptions.
Static Public Member Functions
static String getMessageXML (Exception exception, String endClass) throws ParserConfigurationException, TransformerException
XML ERROR MESSAGE for catch exceptions.
static String getMessageJSON (Exception exception, String endClass)
JSON ERROR MESSAGE for catch exceptions.
static String getMessageTEXT (Exception exception, String endClass)
TEXT ERROR MESSAGE for catch exceptions.
Detailed Description
ERROR MESSAGE for catch exceptions.
Author
Florian Thiery M.Sc.
i3mainz - Institute for Spatial Information and Surveying Technology
Version
18.02.2015
Member Function Documentation
getMessageJSON()
static String getMessageJSON (Exception exception, String endClass) static
JSON ERROR MESSAGE for catch exceptions.
Parameters
exception
endClass
Returns
error message JSON
{
         // START BUILD JSON
         Gson gson = new GsonBuilder().setPrettyPrinting().create();
         JSONObject jsonobj_error = new JSONObject(); // {}
         JSONObject jsonobj_error_data = new JSONObject(); // {}
         JSONArray jsonarray_element = new JSONArray();
         for (StackTraceElement element : exception.getStackTrace()) {
             JSONObject errMessage = new JSONObject();
             errMessage.put("class", element.getClassName());
             errMessage.put("method", element.getMethodName());
             errMessage.put("line", element.getLineNumber());
             jsonarray_element.add(errMessage);
             //jsonarray_element.add(element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber());
             if (element.getClassName().equals(endClass)) {
                 break;
             }
         }
         // get error code
         String code = "";
         String userMessage = "";
         if (exception.toString().contains("NullPointerException")) {
             code = "1";
             userMessage = "some value is not available";
         } else if (exception.toString().contains("ValidateJSONObjectException")) {
             code = "2";
                         String[] ex = exception.toString().split(": ");
             userMessage = "validate JSON object exception: " + ex[1];
         }
         // output
         jsonobj_error.put("errors", jsonobj_error_data);
         jsonobj_error_data.put("internalMessage", exception.toString());
         jsonobj_error_data.put("userMessage", userMessage);
         jsonobj_error_data.put("code", code);
         jsonobj_error_data.put("developerInfo", jsonarray_element);
         // OUTPUT AS pretty print JSON
         return gson.toJson(jsonobj_error);
     }
Referenced by ImportcsvResource.csvUpload(), ImportcsvResource.csvUploadDirectResponse(), ImportcsvResource.csvUploadUpdate(), AgentsResource.deleteAgent(), LabelsResource.deleteLabel(), VocabsResource.deleteVocabulary(), AgentsResource.getAgent(), AgentsResource.getAgent_JSON(), AgentsResource.getAgent_XML(), AgentsResource.getAgentRDF_JSONLD(), AgentsResource.getAgentRDF_JSONRDF(), AgentsResource.getAgentRDF_N3(), AgentsResource.getAgentRDF_Turtle(), AgentsResource.getAgentRDF_XML(), AgentsResource.getAgents(), RestResource.getAPIpage(), InfoResource.getAPIpage(), DumpResource.getDump(), AuthResource.getHash(), RetcatResource.getInfoArchwort(), RetcatResource.getInfoBGS(), RetcatResource.getInfoChronontology(), RetcatResource.getInfoDBpedia(), RetcatResource.getInfoExtern(), RetcatResource.getInfoGeoNames(), RetcatResource.getInfoGetty(), RetcatResource.getInfoHeritageData(), RetcatResource.getInfoLabelingSystem(), RetcatResource.getInfoPelagios(), RetcatResource.getInfoPersonDB(), RetcatResource.getInfoSkosmosFao(), RetcatResource.getInfoSkosmosFinto(), RetcatResource.getInfoSkosmosUnesco(), RetcatResource.getInfoWikidata(), LabelsResource.getLabel(), LabelsResource.getLabel_BNR(), LabelsResource.getLabel_JSON(), LabelsResource.getLabel_Relations(), LabelsResource.getLabel_XML(), LabelsResource.getLabelRDF_JSONLD(), LabelsResource.getLabelRDF_JSONRDF(), LabelsResource.getLabelRDF_N3(), LabelsResource.getLabelRDF_Turtle(), LabelsResource.getLabelRDF_XML(), LabelsResource.getLabels(), LanguagesResource.getLanguages(), LicensesResource.getLicenses(), DumpResource.getList(), RetcatResource.getQueryResultsARCHWORT(), RetcatResource.getQueryResultsBGS(), RetcatResource.getQueryResultsCHRONONTOLOGY(), RetcatResource.getQueryResultsDBPEDIA(), RetcatResource.getQueryResultsGEONAMES(), RetcatResource.getQueryResultsGettyAAT(), RetcatResource.getQueryResultsGettyTGN(), RetcatResource.getQueryResultsGettyULAN(), RetcatResource.getQueryResultsHeritagedataHE(), RetcatResource.getQueryResultsHeritagedataRCAHMS(), RetcatResource.getQueryResultsHeritagedataRCAHMW(), RetcatResource.getQueryResultsHTML(), RetcatResource.getQueryResultsLabelingSystem(), RetcatResource.getQueryResultsLabelingSystemVocabulary(), RetcatResource.getQueryResultsPELAGIOS(), RetcatResource.getQueryResultsPERSONDB(), RetcatResource.getQueryResultsSkosmosFAO(), RetcatResource.getQueryResultsSkosmosFINTO(), RetcatResource.getQueryResultsSkosmosUNESCO(), RetcatResource.getQueryResultsWIKIDATA(), SearchResource.getResultsLabelingSystem(), RetcatResource.getRetcatDetails(), RetcatResource.getRetcatGroups(), RetcatResource.getRetcatList(), RetcatResource.getRetcatListByVocabulary(), RetcatResource.getRetcatListByVocabularyForList(), RetcatResource.getRetcatQualities(), RetcatResource.getRetcatTypes(), RevisionsResource.getRevision(), RevisionsResource.getRevision_JSON(), RevisionsResource.getRevision_XML(), RevisionsResource.getRevisionRDF_JSONLD(), RevisionsResource.getRevisionRDF_JSONRDF(), RevisionsResource.getRevisionRDF_N3(), RevisionsResource.getRevisionRDF_Turtle(), RevisionsResource.getRevisionRDF_XML(), RevisionsResource.getRevisions(), SparqlResource.getSPARQLresultsGET(), SparqlResource.getSPARQLresultsPOST(), DumpResource.getStatus(), AutocompleteResource.getSuggestionsForAgents(), AutocompleteResource.getSuggestionsForLabels(), AutocompleteResource.getSuggestionsForLabelsFilter(), AutocompleteResource.getSuggestionsForVocabs(), VocabsResource.getVocabularies(), VocabsResource.getVocabulary(), VocabsResource.getVocabulary_JSON(), VocabsResource.getVocabulary_XML(), VocabsResource.getVocabularyRDF_JSONLD(), VocabsResource.getVocabularyRDF_JSONRDF(), VocabsResource.getVocabularyRDF_N3(), VocabsResource.getVocabularyRDF_SKOS(), VocabsResource.getVocabularyRDF_Turtle(), VocabsResource.getVocabularyRDF_XML(), RetcatResource.getWaybackLink(), TestsResource.initTest(), AuthResource.loginUser(), AuthResource.logoutUser(), AgentsResource.postAgent(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), RetcatResource.setRetcatForVocabulary(), RetcatResource.setRetcatForVocabularyForList(), DumpResource.startDumping(), AuthResource.statusUser(), DumpResource.stopDumping(), AgentsResource.updateAgent(), LabelsResource.updateLabel(), RetcatResource.updateRetcatForVocabulary(), RetcatResource.updateRetcatForVocabularyForList(), and VocabsResource.updateVocabulary().
getMessageTEXT()
static String getMessageTEXT (Exception exception, String endClass) static
TEXT ERROR MESSAGE for catch exceptions.
Parameters
exception
endClass
Returns
error message TEXT
{
         String message = "error\n";
         message += "message: \"" + exception.toString() + "\"";
         for (StackTraceElement element : exception.getStackTrace()) {
             message += "\ndescription: \"" + element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber() + "\"";
             if (element.getClassName().equals(endClass)) {
                 break;
             }
         }
         return message;
     }
getMessageXML()
static String getMessageXML (Exception exception, String endClass) throws ParserConfigurationException, TransformerException static
XML ERROR MESSAGE for catch exceptions.
Parameters
exception
endClass
Returns
error message XML
Exceptions
javax.xml.parsers.ParserConfigurationException
javax.xml.transform.TransformerException
{
         XMLBuilder xml = XMLBuilder.create("error")
                 .e("message")
                 .t(exception.toString())
                 .up();
         for (StackTraceElement element : exception.getStackTrace()) {
             xml.e("description")
                     .t(element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber())
                     .up();
             if (element.getClassName().equals(endClass)) {
                 break;
             }
         }
         return xml.asString();
     }