labelingsystem-server: RetcatResource Class Reference
RetcatResource Class Reference
Public Member Functions
Response getRetcatList ()
Response getRetcatDetails (@PathParam("retcat") String retcat)
Response getRetcatQualities ()
Response getRetcatGroups ()
Response getRetcatTypes ()
Response getRetcatListByVocabulary (@PathParam("vocabulary") String vocabulary)
Response setRetcatForVocabulary (@PathParam("vocabulary") String vocabulary, String json)
Response updateRetcatForVocabulary (@PathParam("vocabulary") String vocabulary, String json)
Response getRetcatListByVocabularyForList (@PathParam("vocabulary") String vocabulary)
Response setRetcatForVocabularyForList (@PathParam("vocabulary") String vocabulary, String json)
Response updateRetcatForVocabularyForList (@PathParam("vocabulary") String vocabulary, String json)
Response getWaybackLink (@QueryParam("url") String url)
Response getQueryResultsLabelingSystem (@QueryParam("query") String searchword)
Response getQueryResultsLabelingSystemVocabulary (@QueryParam("query") String searchword, @PathParam("vocabulary") String vocabulary)
Response getInfoLabelingSystem (@QueryParam("uri") String uri)
Response getQueryResultsGettyAAT (@QueryParam("query") String searchword)
Response getQueryResultsGettyTGN (@QueryParam("query") String searchword)
Response getQueryResultsGettyULAN (@QueryParam("query") String searchword)
Response getInfoGetty (@QueryParam("uri") String uri)
Response getQueryResultsHeritagedataHE (@QueryParam("query") String searchword)
Response getQueryResultsHeritagedataRCAHMS (@QueryParam("query") String searchword)
Response getQueryResultsHeritagedataRCAHMW (@QueryParam("query") String searchword)
Response getInfoHeritageData (@QueryParam("uri") String uri)
Response getQueryResultsCHRONONTOLOGY (@QueryParam("query") String searchword)
Response getInfoChronontology (@QueryParam("uri") String uri)
Response getQueryResultsPELAGIOS (@QueryParam("query") String searchword)
Response getInfoPelagios (@QueryParam("uri") String uri)
Response getQueryResultsSkosmosFINTO (@QueryParam("query") String searchword)
Response getInfoSkosmosFinto (@QueryParam("uri") String uri)
Response getQueryResultsSkosmosFAO (@QueryParam("query") String searchword)
Response getInfoSkosmosFao (@QueryParam("uri") String uri)
Response getQueryResultsSkosmosUNESCO (@QueryParam("query") String searchword)
Response getInfoSkosmosUnesco (@QueryParam("uri") String uri)
Response getQueryResultsARCHWORT (@QueryParam("query") String searchword)
Response getInfoArchwort (@QueryParam("uri") String uri)
Response getQueryResultsBGS (@QueryParam("query") String searchword)
Response getInfoBGS (@QueryParam("uri") String uri)
Response getQueryResultsDBPEDIA (@QueryParam("query") String searchword)
Response getInfoDBpedia (@QueryParam("uri") String uri)
Response getQueryResultsWIKIDATA (@QueryParam("query") String searchword)
Response getInfoWikidata (@QueryParam("uri") String uri)
Response getQueryResultsGEONAMES (@QueryParam("query") String searchword)
Response getInfoGeoNames (@QueryParam("uri") String uri)
Response getQueryResultsPERSONDB (@QueryParam("query") String searchword)
Response getInfoPersonDB (@QueryParam("uri") String uri)
Response getQueryResultsHTML (@QueryParam("query") String url)
Response getInfoExtern (@QueryParam("url") String url, @QueryParam("type") String type)
Static Public Member Functions
static int getLimit ()
Private Member Functions
JSONArray fillOutputJSONforQuery (Map< String, SuggestionItem > autosuggests)
Static Private Attributes
static final int LIMIT = 20
Member Function Documentation
fillOutputJSONforQuery()
JSONArray fillOutputJSONforQuery (Map< String, SuggestionItem > autosuggests) private
{
                 JSONArray outArray = new JSONArray();
                 int i = 0;
                 for (Map.Entry<String, SuggestionItem> entry : autosuggests.entrySet()) {
                         if (i < LIMIT) {
                                 SuggestionItem tmpAS = entry.getValue();
                                 JSONObject suggestionObject = new JSONObject();
                                 // url
                                 suggestionObject.put("uri", tmpAS.getURL());
                                 // labels
                                 suggestionObject.put("label", tmpAS.getLabels().iterator().next());
                                 // scheme
                                 suggestionObject.put("scheme", tmpAS.getSchemeTitle());
                                 // creator
                                 suggestionObject.put("orcid", tmpAS.getOrcid());
                                 suggestionObject.put("creator", tmpAS.getCreator());
                                 // descriptions
                                 if (tmpAS.getDescriptions().size() > 0) {
                                         suggestionObject.put("description", tmpAS.getDescriptions().iterator().next());
                                 } else {
                                         suggestionObject.put("description", "");
                                 }
                                 // language
                                 suggestionObject.put("lang", tmpAS.getLanguage());
                                 // type
                                 suggestionObject.put("type", tmpAS.getType());
                                 // group
                                 suggestionObject.put("group", tmpAS.getGroup());
                                 // quality
                                 suggestionObject.put("quality", tmpAS.getQuality());
                                 // broader
                                 Set broaderTerms = tmpAS.getBroaderTerms();
                                 JSONArray broaderArrayNew = new JSONArray();
                                 if (broaderTerms.size() > 0) {
                                         for (Object element : broaderTerms) {
                                                 Map hm = (Map) element;
                                                 Iterator entries = hm.entrySet().iterator();
                                                 while (entries.hasNext()) {
                                                         Map.Entry thisEntry = (Map.Entry) entries.next();
                                                         String key = (String) thisEntry.getKey();
                                                         String value = (String) thisEntry.getValue();
                                                         JSONObject broaderObjectTmp = new JSONObject();
                                                         broaderObjectTmp.put("uri", key);
                                                         broaderObjectTmp.put("label", value);
                                                         broaderArrayNew.add(broaderObjectTmp);
                                                 }
                                         }
                                 }
                                 suggestionObject.put("broaderTerms", broaderArrayNew);
                                 // narrower
                                 Set narrowerTerms = tmpAS.getNarrowerTerms();
                                 JSONArray narrowerArrayNew = new JSONArray();
                                 if (narrowerTerms.size() > 0) {
                                         for (Object element : narrowerTerms) {
                                                 Map hm = (Map) element;
                                                 Iterator entries = hm.entrySet().iterator();
                                                 while (entries.hasNext()) {
                                                         Map.Entry thisEntry = (Map.Entry) entries.next();
                                                         String key = (String) thisEntry.getKey();
                                                         String value = (String) thisEntry.getValue();
                                                         JSONObject narrowerObjectTmp = new JSONObject();
                                                         narrowerObjectTmp.put("uri", key);
                                                         narrowerObjectTmp.put("label", value);
                                                         narrowerArrayNew.add(narrowerObjectTmp);
                                                 }
                                         }
                                 }
                                 suggestionObject.put("narrowerTerms", narrowerArrayNew);
                                 // add information to output array
                                 outArray.add(suggestionObject);
                                 i++;
                         }
                 }
                 return outArray;
         }
getInfoArchwort()
Response getInfoArchwort (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Archwort.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Archwort.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoBGS()
Response getInfoBGS (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_BGSLinkedData.info().
{
                 try {
                         JSONObject jsonOut = Retcat_BGSLinkedData.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoChronontology()
Response getInfoChronontology (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_ChronOntology.info().
{
                 try {
                         JSONObject jsonOut = Retcat_ChronOntology.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoDBpedia()
Response getInfoDBpedia (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Dbpedia.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Dbpedia.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoExtern()
Response getInfoExtern (@QueryParam("url") String url, @QueryParam("type") String type)
References Logging.getMessageJSON(), and Retcat_HTML.info().
{
                 try {
                         JSONObject jsonOut = Retcat_HTML.info(url);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoGeoNames()
Response getInfoGeoNames (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_GeoNames.info().
{
                 try {
                         JSONObject jsonOut = Retcat_GeoNames.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoGetty()
Response getInfoGetty (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Getty.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Getty.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoHeritageData()
Response getInfoHeritageData (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_HeritageData.info().
{
                 try {
                         JSONObject jsonOut = Retcat_HeritageData.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoLabelingSystem()
Response getInfoLabelingSystem (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_LabelingSystem.info().
{
                 try {
                         JSONObject jsonOut = Retcat_LabelingSystem.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoPelagios()
Response getInfoPelagios (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Pleiades.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Pleiades.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoPersonDB()
Response getInfoPersonDB (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_PersonDB.info().
{
                 try {
                         JSONObject jsonOut = Retcat_PersonDB.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoSkosmosFao()
Response getInfoSkosmosFao (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Fao.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Fao.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoSkosmosFinto()
Response getInfoSkosmosFinto (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Finto.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Finto.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoSkosmosUnesco()
Response getInfoSkosmosUnesco (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Unesco.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Unesco.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getInfoWikidata()
Response getInfoWikidata (@QueryParam("uri") String uri)
References Logging.getMessageJSON(), and Retcat_Wikidata.info().
{
                 try {
                         JSONObject jsonOut = Retcat_Wikidata.info(uri);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getLimit()
static int getLimit () static
Referenced by Retcat_ChronOntology.query(), Retcat_Unesco.query(), Retcat_Pleiades.query(), Retcat_Dbpedia.query(), Retcat_Finto.query(), Retcat_Fao.query(), and Retcat_GeoNames.query().
{
                 return LIMIT;
         }
getQueryResultsARCHWORT()
Response getQueryResultsARCHWORT (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Archwort.info(), and Retcat_Archwort.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Archwort.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Archwort.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsBGS()
Response getQueryResultsBGS (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_BGSLinkedData.info(), and Retcat_BGSLinkedData.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_BGSLinkedData.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_BGSLinkedData.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsCHRONONTOLOGY()
Response getQueryResultsCHRONONTOLOGY (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_ChronOntology.info(), and Retcat_ChronOntology.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_ChronOntology.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_ChronOntology.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsDBPEDIA()
Response getQueryResultsDBPEDIA (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Dbpedia.info(), and Retcat_Dbpedia.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Dbpedia.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Dbpedia.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsGEONAMES()
Response getQueryResultsGEONAMES (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_GeoNames.info(), and Retcat_GeoNames.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_GeoNames.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_GeoNames.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsGettyAAT()
Response getQueryResultsGettyAAT (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Getty.info(), and Retcat_Getty.queryAAT().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Getty.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Getty.queryAAT(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsGettyTGN()
Response getQueryResultsGettyTGN (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Getty.info(), and Retcat_Getty.queryTGN().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Getty.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Getty.queryTGN(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsGettyULAN()
Response getQueryResultsGettyULAN (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Getty.info(), and Retcat_Getty.queryULAN().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Getty.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Getty.queryULAN(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsHeritagedataHE()
Response getQueryResultsHeritagedataHE (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_HeritageData.info(), and Retcat_HeritageData.queryHE().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_HeritageData.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_HeritageData.queryHE(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsHeritagedataRCAHMS()
Response getQueryResultsHeritagedataRCAHMS (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_HeritageData.info(), and Retcat_HeritageData.queryRCAHMS().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_HeritageData.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_HeritageData.queryRCAHMS(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsHeritagedataRCAHMW()
Response getQueryResultsHeritagedataRCAHMW (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_HeritageData.info(), and Retcat_HeritageData.queryRCAHMW().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_HeritageData.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_HeritageData.queryRCAHMW(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsHTML()
Response getQueryResultsHTML (@QueryParam("query") String url)
References Logging.getMessageJSON(), and Retcat_HTML.query().
{
                 try {
                         Map<String, SuggestionItem> autosuggests = Retcat_HTML.query(url);
                         JSONArray outArray = new JSONArray();
                         outArray = fillOutputJSONforQuery(autosuggests);
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsLabelingSystem()
Response getQueryResultsLabelingSystem (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_LabelingSystem.info(), and Retcat_LabelingSystem.queryAll().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_LabelingSystem.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_LabelingSystem.queryAll(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsLabelingSystemVocabulary()
Response getQueryResultsLabelingSystemVocabulary (@QueryParam("query") String searchword, @PathParam("vocabulary") String vocabulary)
References Logging.getMessageJSON(), Retcat_LabelingSystem.info(), and Retcat_LabelingSystem.queryVocab().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_LabelingSystem.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_LabelingSystem.queryVocab(searchword, vocabulary);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsPELAGIOS()
Response getQueryResultsPELAGIOS (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Pleiades.info(), and Retcat_Pleiades.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Pleiades.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Pleiades.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsPERSONDB()
Response getQueryResultsPERSONDB (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_PersonDB.info(), and Retcat_PersonDB.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_PersonDB.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_PersonDB.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsSkosmosFAO()
Response getQueryResultsSkosmosFAO (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Fao.info(), and Retcat_Fao.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Fao.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Fao.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsSkosmosFINTO()
Response getQueryResultsSkosmosFINTO (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Finto.info(), and Retcat_Finto.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Finto.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Finto.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsSkosmosUNESCO()
Response getQueryResultsSkosmosUNESCO (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Unesco.info(), and Retcat_Unesco.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Unesco.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Unesco.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getQueryResultsWIKIDATA()
Response getQueryResultsWIKIDATA (@QueryParam("query") String searchword)
References Logging.getMessageJSON(), Retcat_Wikidata.info(), and Retcat_Wikidata.query().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         if (searchword.startsWith("uri:")) {
                                 outArray.add(Retcat_Wikidata.info(searchword.replace("uri:", "")));
                                 outArray.remove(new JSONObject());
                         } else {
                                 Map<String, SuggestionItem> autosuggests = Retcat_Wikidata.query(searchword);
                                 outArray = fillOutputJSONforQuery(autosuggests);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatDetails()
Response getRetcatDetails (@PathParam("retcat") String retcat)
References LocalRetcatItems.getLocalCatalogue(), and Logging.getMessageJSON().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                 if (item.getName().equals(retcat)) {
                                         JSONObject tmpRETCAT = new JSONObject();
                                         tmpRETCAT.put("name", item.getName());
                                         tmpRETCAT.put("description", item.getDescription());
                                         tmpRETCAT.put("queryURL", item.getQueryURL());
                                         tmpRETCAT.put("labelURL", item.getLabelURL());
                                         tmpRETCAT.put("prefix", item.getPrefix());
                                         tmpRETCAT.put("group", item.getGroup());
                                         tmpRETCAT.put("type", item.getType());
                                         tmpRETCAT.put("language", item.getLanguage());
                                         tmpRETCAT.put("quality", item.getQuality());
                                         tmpRETCAT.put("default", item.getDefaultValue());
                                         outArray.add(tmpRETCAT);
                                 }
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatGroups()
Response getRetcatGroups ()
References LocalRetcatItems.getLocalCatalogue(), and Logging.getMessageJSON().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         HashSet<String> groupList = new HashSet();
                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                 groupList.add(item.getGroup());
                         }
                         for (String item : groupList) {
                                 outArray.add(item);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatList()
Response getRetcatList ()
References LocalRetcatItems.getLocalCatalogue(), and Logging.getMessageJSON().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         // add items
                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                 JSONObject tmpRETCAT = new JSONObject();
                                 tmpRETCAT.put("name", item.getName());
                                 tmpRETCAT.put("description", item.getDescription());
                                 tmpRETCAT.put("queryURL", item.getQueryURL());
                                 tmpRETCAT.put("labelURL", item.getLabelURL());
                                 tmpRETCAT.put("prefix", item.getPrefix());
                                 tmpRETCAT.put("group", item.getGroup());
                                 tmpRETCAT.put("type", item.getType());
                                 tmpRETCAT.put("language", item.getLanguage());
                                 tmpRETCAT.put("quality", item.getQuality());
                                 tmpRETCAT.put("default", item.getDefaultValue());
                                 outArray.add(tmpRETCAT);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatListByVocabulary()
Response getRetcatListByVocabulary (@PathParam("vocabulary") String vocabulary)
References LocalRetcatItems.getLocalCatalogue(), Logging.getMessageJSON(), and SQlite.getRetcatByVocabulary().
{
                 try {
                         // output json
                         JSONArray outArray = new JSONArray();
                         // get retcat items
                         String newRetcatString = SQlite.getRetcatByVocabulary(vocabulary);
                         if (newRetcatString != null) {
                                 String[] retcatItems = newRetcatString.split(",");
                                 // set data
                                 for (String vocItem : retcatItems) {
                                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                                 if (item.getName().equals(vocItem)) {
                                                         JSONObject tmpRETCAT = new JSONObject();
                                                         tmpRETCAT.put("name", item.getName());
                                                         tmpRETCAT.put("description", item.getDescription());
                                                         tmpRETCAT.put("queryURL", item.getQueryURL());
                                                         tmpRETCAT.put("labelURL", item.getLabelURL());
                                                         tmpRETCAT.put("prefix", item.getPrefix());
                                                         tmpRETCAT.put("group", item.getGroup());
                                                         tmpRETCAT.put("type", item.getType());
                                                         tmpRETCAT.put("language", item.getLanguage());
                                                         tmpRETCAT.put("quality", item.getQuality());
                                                         tmpRETCAT.put("default", item.getDefaultValue());
                                                         outArray.add(tmpRETCAT);
                                                 }
                                         }
                                 }
                         }
                         // add own vocabulary
                         JSONObject tmpRETCAT = new JSONObject();
                         tmpRETCAT.put("name", "this." + vocabulary);
                         tmpRETCAT.put("description", "this vocabulary");
                         tmpRETCAT.put("default", true);
                         outArray.add(tmpRETCAT);
                         // output
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatListByVocabularyForList()
Response getRetcatListByVocabularyForList (@PathParam("vocabulary") String vocabulary)
References Logging.getMessageJSON(), and SQlite.getRetcatByVocabularyForList().
{
                 try {
                         JSONObject outObject = new JSONObject();
                         String vocabID = SQlite.getRetcatByVocabularyForList(vocabulary);
                         if (vocabID != null) {
                                 outObject.put("id", vocabID);
                         } else {
                                 outObject.put("id", vocabulary);
                         }
                         // output
                         return Response.ok(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatQualities()
Response getRetcatQualities ()
References LocalRetcatItems.getLocalCatalogue(), and Logging.getMessageJSON().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         HashSet<String> qualityList = new HashSet();
                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                 qualityList.add(item.getQuality());
                         }
                         for (String item : qualityList) {
                                 outArray.add(item);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getRetcatTypes()
Response getRetcatTypes ()
References LocalRetcatItems.getLocalCatalogue(), and Logging.getMessageJSON().
{
                 try {
                         JSONArray outArray = new JSONArray();
                         HashSet<String> groupList = new HashSet();
                         for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                 groupList.add(item.getType());
                         }
                         for (String item : groupList) {
                                 outArray.add(item);
                         }
                         return Response.ok(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getWaybackLink()
Response getWaybackLink (@QueryParam("url") String url)
References LocalRetcatItems.getLocalCatalogue(), Logging.getMessageJSON(), and ConfigProperties.getPropertyParam().
{
                 try {
                         // check if url is item in retcat
                         List<RetcatItem> retcatlist = LocalRetcatItems.getLocalCatalogue();
                         for (RetcatItem item : retcatlist) {
                                 if (url.contains(item.getPrefix())) {
                                         throw new WaybacklinkException("item match in reference thesaurus catalog");
                                 }
                         }
                         // get waybacklink
                         URL obj = new URL(ConfigProperties.getPropertyParam("waybackapi").replace("$url", url));
             HttpURLConnection con = (HttpURLConnection) obj.openConnection();
             con.setRequestMethod("GET");
             con.setRequestProperty("Accept", "application/json");
             BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream(), "UTF8"));
                         String inputLine;
                         StringBuilder response = new StringBuilder();
                         while ((inputLine = in.readLine()) != null) {
                                 response.append(inputLine);
                         }
                         in.close();
                         // init output
                         JSONObject jsonOut = new JSONObject();
                         JSONObject jsonObject = (JSONObject) new JSONParser().parse(response.toString());
                         JSONObject resultsObject = (JSONObject) jsonObject.get("archived_snapshots");
                         JSONObject resultsObject2 = (JSONObject) resultsObject.get("closest");
                         String wburi = null;
                         try {
                                 wburi = (String) resultsObject2.get("url");
                         } catch (Exception e) {
                                 throw new WaybacklinkException("no wayback url available");
                         }
                         jsonOut.put("uri", wburi);
                         return Response.ok(jsonOut).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.NOT_FOUND).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
setRetcatForVocabulary()
Response setRetcatForVocabulary (@PathParam("vocabulary") String vocabulary, String json)
References SQlite.deleteRetcatEntry(), LocalRetcatItems.getLocalCatalogue(), Logging.getMessageJSON(), SQlite.getRetcatByVocabulary(), and SQlite.insertRetcatString().
{
                 try {
                         // db string
                         String retcatString = "";
                         // parse json
                         JSONArray retcatArray = (JSONArray) new JSONParser().parse(json);
                         for (Object itemObject : retcatArray) {
                                 JSONObject tmpObject = (JSONObject) itemObject;
                                 retcatString += tmpObject.get("name") + ",";
                         }
                         retcatString = retcatString.substring(0, retcatString.length() - 1);
                         // sqlite db action
                         SQlite.deleteRetcatEntry(vocabulary);
                         SQlite.insertRetcatString(vocabulary, retcatString);
                         String newRetcatString = SQlite.getRetcatByVocabulary(vocabulary);
                         String[] retcatItems = newRetcatString.split(",");
                         // output json
                         JSONArray outArray = new JSONArray();
                         // set data
                         for (String vocItem : retcatItems) {
                                 for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                         if (item.getName().equals(vocItem)) {
                                                 JSONObject tmpRETCAT = new JSONObject();
                                                 tmpRETCAT.put("name", item.getName());
                                                 tmpRETCAT.put("description", item.getDescription());
                                                 tmpRETCAT.put("queryURL", item.getQueryURL());
                                                 tmpRETCAT.put("labelURL", item.getLabelURL());
                                                 tmpRETCAT.put("prefix", item.getPrefix());
                                                 tmpRETCAT.put("group", item.getGroup());
                                                 tmpRETCAT.put("type", item.getType());
                                                 tmpRETCAT.put("language", item.getLanguage());
                                                 tmpRETCAT.put("quality", item.getQuality());
                                                 outArray.add(tmpRETCAT);
                                         }
                                 }
                         }
                         // add own vocabulary
                         JSONObject tmpRETCAT = new JSONObject();
                         tmpRETCAT.put("name", "this." + vocabulary);
                         tmpRETCAT.put("description", "this vocabulary");
                         outArray.add(tmpRETCAT);
                         // output
                         return Response.status(Response.Status.CREATED).entity(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
setRetcatForVocabularyForList()
Response setRetcatForVocabularyForList (@PathParam("vocabulary") String vocabulary, String json)
References SQlite.deleteRetcatEntryForList(), Logging.getMessageJSON(), SQlite.getRetcatByVocabularyForList(), and SQlite.insertRetcatStringForList().
{
                 try {
                         JSONObject obj = (JSONObject) new JSONParser().parse(json);
                         String vocabID = (String) obj.get("id");
                         // sqlite db action
                         SQlite.deleteRetcatEntryForList(vocabulary);
                         SQlite.insertRetcatStringForList(vocabulary, vocabID);
                         // get data
                         JSONObject outObject = new JSONObject();
                         vocabID = SQlite.getRetcatByVocabularyForList(vocabulary);
                         outObject.put("id", vocabID);
                         // output
                         return Response.status(Response.Status.CREATED).entity(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
updateRetcatForVocabulary()
Response updateRetcatForVocabulary (@PathParam("vocabulary") String vocabulary, String json)
References SQlite.deleteRetcatEntry(), LocalRetcatItems.getLocalCatalogue(), Logging.getMessageJSON(), SQlite.getRetcatByVocabulary(), and SQlite.insertRetcatString().
{
                 try {
                         // db string
                         String retcatString = "";
                         // parse json
                         JSONArray retcatArray = (JSONArray) new JSONParser().parse(json);
                         for (Object itemObject : retcatArray) {
                                 JSONObject tmpObject = (JSONObject) itemObject;
                                 retcatString += tmpObject.get("name") + ",";
                         }
                         retcatString = retcatString.substring(0, retcatString.length() - 1);
                         // sqlite db action
                         SQlite.deleteRetcatEntry(vocabulary);
                         SQlite.insertRetcatString(vocabulary, retcatString);
                         String newRetcatString = SQlite.getRetcatByVocabulary(vocabulary);
                         String[] retcatItems = newRetcatString.split(",");
                         // output json
                         JSONArray outArray = new JSONArray();
                         // set data
                         for (String vocItem : retcatItems) {
                                 for (RetcatItem item : LocalRetcatItems.getLocalCatalogue()) {
                                         if (item.getName().equals(vocItem)) {
                                                 JSONObject tmpRETCAT = new JSONObject();
                                                 tmpRETCAT.put("name", item.getName());
                                                 tmpRETCAT.put("description", item.getDescription());
                                                 tmpRETCAT.put("queryURL", item.getQueryURL());
                                                 tmpRETCAT.put("labelURL", item.getLabelURL());
                                                 tmpRETCAT.put("prefix", item.getPrefix());
                                                 tmpRETCAT.put("group", item.getGroup());
                                                 tmpRETCAT.put("type", item.getType());
                                                 tmpRETCAT.put("language", item.getLanguage());
                                                 tmpRETCAT.put("quality", item.getQuality());
                                                 outArray.add(tmpRETCAT);
                                         }
                                 }
                         }
                         // add own vocabulary
                         JSONObject tmpRETCAT = new JSONObject();
                         tmpRETCAT.put("name", "this." + vocabulary);
                         tmpRETCAT.put("description", "this vocabulary");
                         outArray.add(tmpRETCAT);
                         // output
                         return Response.status(Response.Status.CREATED).entity(outArray).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
updateRetcatForVocabularyForList()
Response updateRetcatForVocabularyForList (@PathParam("vocabulary") String vocabulary, String json)
References SQlite.deleteRetcatEntryForList(), Logging.getMessageJSON(), SQlite.getRetcatByVocabularyForList(), and SQlite.insertRetcatStringForList().
{
                 try {
                         JSONObject obj = (JSONObject) new JSONParser().parse(json);
                         String vocabID = (String) obj.get("id");
                         // sqlite db action
                         SQlite.deleteRetcatEntryForList(vocabulary);
                         SQlite.insertRetcatStringForList(vocabulary, vocabID);
                         // get data
                         JSONObject outObject = new JSONObject();
                         vocabID = SQlite.getRetcatByVocabularyForList(vocabulary);
                         outObject.put("id", vocabID);
                         // output
                         return Response.status(Response.Status.CREATED).entity(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.RetcatResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
Member Data Documentation
LIMIT
final int LIMIT = 20 static private