labelingsystem-server: DumpResource Class Reference
DumpResource Class Reference
Public Member Functions
Response getList ()
Response getDump (@PathParam("repo") String repo)
Response getStatus (@QueryParam("mode") String mode)
Response startDumping ()
Response stopDumping ()
void start () throws InterruptedException, IOException
void status () throws InterruptedException, IOException
void stop ()
void listFilesForFolder ()
Static Public Member Functions
static void listDumpFilesDeleteForMax () throws IOException
static int getNumberOfStatements () throws MalformedURLException, IOException
Static Public Attributes
static String mode = "start"
static String out
static long startTime = System.currentTimeMillis()
static boolean dumping = false
static String fileDir = ""
static String filePath = ""
static String tmpDirString = "tmpDir_1"
static String tmpDirString2 = "tmpDir_2"
static String tmpDirPath = ""
static String tmpDirPath2 = ""
static String downloadLink = ""
static String size_url = ""
static long sleepTimeInMills = 43200000
static String lastDump = ""
static String lastDumpTime = ""
static String numberOfTriples = ""
static int dumbNo = -1
Static Private Attributes
static final List< String > fileList = new ArrayList<String>()
static int maxDumps = 100
Member Function Documentation
getDump()
Response getDump (@PathParam("repo") String repo)
References Logging.getMessageJSON(), and Dump.writeFile().
{
                 try {
                         String dumpFile = Dump.writeFile(repo);
                         JSONObject out = new JSONObject();
                         out.put("file", dumpFile);
                         return Response.ok(out).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.DumpResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getList()
Response getList ()
References Logging.getMessageJSON(), and ConfigProperties.getPropertyParam().
{
                 try {
                         fileDir = ConfigProperties.getPropertyParam("dump_server");
                         String html_header = "<html>";
                         html_header += "<head>";
                         html_header += "</head>";
                         html_header += "<body>";
                         String html_footer = "</body>";
                         html_footer += "</html>";
                         listFilesForFolder();
                         out = "<h1>Index of Labeling System Dumps</h1>";
                         if (fileList.size() > 0) {
                                 out += "<table style=\"width:75%\" border='1'>";
                                 out += "<tr><th>Name</th><th>Last modified</th><th>Size</th></tr>";
                                 for (String file : fileList) {
                                         out += "<tr>"
                                                         + "<td width='25%'><a href='" + ConfigProperties.getPropertyParam("dump_web") + file.split("#")[0] + "'>" + file.split("#")[0] + "</a></td>"
                                                         + "<td width='25%'>" + file.split("#")[2] + "</td>"
                                                         + "<td width='25%'>" + file.split("#")[1] + " KB</td>"
                                                         + "</tr>";
                                 }
                                 out += "</table>";
                         }
                         return Response.ok(html_header + out + html_footer).header("Content-Type", "text/html;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.DumpResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
getNumberOfStatements()
static int getNumberOfStatements () throws MalformedURLException, IOException static
Referenced by LSDump.writeFile().
{
                 try {
                         URL obj = new URL(size_url);
                         HttpURLConnection con = (HttpURLConnection) obj.openConnection();
                         con.setRequestMethod("GET");
                         BufferedReader in = new BufferedReader(
                                         new InputStreamReader(con.getInputStream()));
                         String inputLine;
                         StringBuilder response = new StringBuilder();
                         while ((inputLine = in.readLine()) != null) {
                                 response.append(inputLine);
                         }
                         in.close();
                         int size = Integer.parseInt(response.toString());
                         return size;
                 } catch (Exception e) {
                         throw new NullPointerException();
                 }
         }
getStatus()
Response getStatus (@QueryParam("mode") String mode)
References Logging.getMessageJSON().
{
                 try {
                         status();
                         JSONObject outObject = new JSONObject();
                         outObject.put("message", out);
                         return Response.ok(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.DumpResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
listDumpFilesDeleteForMax()
static void listDumpFilesDeleteForMax () throws IOException static
Referenced by LSDump.writeFile().
{
                 fileList.clear();
                 File directory = new File(fileDir);
                 File[] files = directory.listFiles((FileFilter) FileFileFilter.FILE);
                 Arrays.sort(files, LastModifiedFileComparator.LASTMODIFIED_REVERSE);
                 for (File file : files) {
                         if (!file.getName().contains("labelingsystem-latest")) {
                                 fileList.add(file.getName());
                         }
                 }
                 boolean tmp = true;
                 while (tmp) {
                         if (fileList.size() >= maxDumps) {
                                 File fileDelete = new File(fileDir + fileList.get(fileList.size() - 1));
                                 Files.deleteIfExists(fileDelete.toPath());
                                 fileList.remove(fileList.size() - 1);
                         } else {
                                 tmp = false;
                                 break;
                         }
                 }
         }
listFilesForFolder()
void listFilesForFolder ()
{
                 fileList.clear();
                 // http://www.avajava.com/tutorials/lessons/how-do-i-sort-an-array-of-files-according-to-their-last-modified-dates.html
                 File directory = new File(fileDir);
                 File[] files = directory.listFiles((FileFilter) FileFileFilter.FILE);
                 Arrays.sort(files, LastModifiedFileComparator.LASTMODIFIED_REVERSE);
                 for (File file : files) {
                         double filesize = (file.length() / 1024);
                         fileList.add(file.getName() + "#" + filesize + "#" + new Date(file.lastModified()));
                 }
         }
start()
void start () throws InterruptedException, IOException
{
                 (new Thread(new LSDump())).start();
                 long currentTime = System.currentTimeMillis();
                 SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy HH:mm:ss");
                 Date resultdate = new Date(currentTime);
                 System.out.println("started at: " + sdf.format(resultdate));
                 status();
         }
startDumping()
Response startDumping ()
References Logging.getMessageJSON(), and ConfigProperties.getPropertyParam().
{
                 try {
                         fileDir = ConfigProperties.getPropertyParam("dump_server");
                         filePath = ConfigProperties.getPropertyParam("dump_web");
                         downloadLink = ConfigProperties.getPropertyParam("ts_server") + "/repositories/" + ConfigProperties.getPropertyParam("repository") + "/statements?Accept=text/plain";
                         size_url = ConfigProperties.getPropertyParam("ts_server") + "/repositories/" + ConfigProperties.getPropertyParam("repository") + "/size";
                         tmpDirPath = fileDir + "tmpDir_1" + "/";
                         tmpDirPath2 = fileDir + "tmpDir_2" + "/";
                         dumping = true;
                         start();
                         JSONObject outObject = new JSONObject();
                         outObject.put("message", out);
                         return Response.ok(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         stop();
                         dumping = false;
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.DumpResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
status()
void status () throws InterruptedException, IOException
{
                 if (dumping) {
                         SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy HH:mm:ss");
                         Date resultdate = new Date(startTime);
                         if (lastDumpTime.equals("") || lastDump.equals("")) {
                                 out = "started at: " + sdf.format(resultdate);
                         } else {
                                 out = "started at: " + sdf.format(resultdate) + ", last dump at: " + lastDumpTime + ", last dump: " + lastDump;
                         }
                 } else {
                         out = "dumping not started";
                 }
         }
stop()
void stop ()
{
                 if (dumping) {
                         long currentTime = System.currentTimeMillis();
                         SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy HH:mm:ss");
                         Date resultdate = new Date(currentTime);
                         System.out.println("stopped at: " + sdf.format(resultdate));
                         dumping = false;
                         out = "stopped at: " + sdf.format(resultdate);
                 } else {
                         out = "dumping not started";
                 }
         }
stopDumping()
Response stopDumping ()
References Logging.getMessageJSON().
{
                 try {
                         stop();
                         JSONObject outObject = new JSONObject();
                         outObject.put("message", out);
                         return Response.ok(outObject).header("Content-Type", "application/json;charset=UTF-8").build();
                 } catch (Exception e) {
                         stop();
                         dumping = false;
                         return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Logging.getMessageJSON(e, "v1.rest.DumpResource"))
                                         .header("Content-Type", "application/json;charset=UTF-8").build();
                 }
         }
Member Data Documentation
downloadLink
String downloadLink = "" static
Referenced by LSDump.writeFile().
dumbNo
int dumbNo = -1 static
Referenced by LSDump.writeFile().
dumping
boolean dumping = false static
Referenced by LSDump.run(), and LSDump.writeFile().
fileDir
String fileDir = "" static
Referenced by LSDump.writeFile().
fileList
final List<String> fileList = new ArrayList<String>() static private
filePath
String filePath = "" static
Referenced by LSDump.writeFile().
lastDump
String lastDump = "" static
Referenced by LSDump.writeFile().
lastDumpTime
String lastDumpTime = "" static
Referenced by LSDump.writeFile().
maxDumps
int maxDumps = 100 static private
mode
String mode = "start" static
numberOfTriples
String numberOfTriples = "" static
out
String out static
size_url
String size_url = "" static
sleepTimeInMills
long sleepTimeInMills = 43200000 static
Referenced by LSDump.writeFile().
startTime
long startTime = System.currentTimeMillis() static
tmpDirPath
String tmpDirPath = "" static
Referenced by LSDump.writeFile().
tmpDirPath2
String tmpDirPath2 = "" static
Referenced by LSDump.writeFile().
tmpDirString
String tmpDirString = "tmpDir_1" static
Referenced by LSDump.writeFile().
tmpDirString2
String tmpDirString2 = "tmpDir_2" static
Referenced by LSDump.writeFile().