labelingsystem-server: ResourceQueryResource Class Reference
ResourceQueryResource Class Reference
Public Member Functions
Response redirectToRetcat (@QueryParam("retcat") String retcat, @QueryParam("query") String query) throws URISyntaxException, IOException, RepositoryException, MalformedQueryException, QueryEvaluationException, SesameSparqlException, ResourceNotAvailableException, org.eclipse.rdf4j.repository.RepositoryException, org.eclipse.rdf4j.query.MalformedQueryException, org.eclipse.rdf4j.query.QueryEvaluationException, link.labeling.retcat.exceptions.ResourceNotAvailableException
Member Function Documentation
redirectToRetcat()
Response redirectToRetcat (@QueryParam("retcat") String retcat, @QueryParam("query") String query) throws URISyntaxException, IOException, RepositoryException, MalformedQueryException, QueryEvaluationException, SesameSparqlException, ResourceNotAvailableException, org.eclipse.rdf4j.repository.RepositoryException, org.eclipse.rdf4j.query.MalformedQueryException, org.eclipse.rdf4j.query.QueryEvaluationException, link.labeling.retcat.exceptions.ResourceNotAvailableException
References GeneralFunctions.encodeURIComponent(), LocalRetcatItems.getLocalCatalogue(), and ConfigProperties.getPropertyParam().
{
         List<RetcatItem> retcatlist = LocalRetcatItems.getLocalCatalogue();
         boolean match = false;
         if (retcat != null) {
             //ckeck if own vocab
             if (retcat.contains("this.")) {
                 String vocab = retcat.split("this.")[1];
                 query = GeneralFunctions.encodeURIComponent(query);
                 URI targetURIForRedirection = new URI(ConfigProperties.getPropertyParam("api") + "/v1/rtc/query/labelingsystem/" + vocab + "?query=" + query);
                 return Response.temporaryRedirect(targetURIForRedirection).build();
             }
             // look for other endpoints
             for (RetcatItem item : retcatlist) {
                 if (retcat.contains(item.getName())) {
                     query = GeneralFunctions.encodeURIComponent(query);
                     URI targetURIForRedirection = new URI(ConfigProperties.getPropertyParam("api") + item.getQueryURL() + "?query=" + query);
                     return Response.temporaryRedirect(targetURIForRedirection).build();
                 }
             }
         }
         if (!match) {
             URI targetURIForRedirection = new URI(ConfigProperties.getPropertyParam("api") + "/v1/rtc/query/html" + "?url=" + query);
             return Response.temporaryRedirect(targetURIForRedirection).build();
         }
         return Response.ok().build();
     }