labelingsystem-server: Crypt Class Reference
Crypt Class Reference
Static Public Member Functions
static String base64encode (String text)
static String base64decode (String text)
static String SHA1 (String text) throws NoSuchAlgorithmException, UnsupportedEncodingException
static String MD5 (String text) throws NoSuchAlgorithmException, UnsupportedEncodingException
static String generateHash () throws NoSuchAlgorithmException, UnsupportedEncodingException
Static Private Member Functions
static String convertToHex (byte[] data)
Member Function Documentation
base64decode()
static String base64decode (String text) static
{
         try {
             String rez = new String(Base64.decodeBase64(text.getBytes("UTF-8")));
             return rez;
         } catch (IOException e) {
             return null;
         }
     }
base64encode()
static String base64encode (String text) static
{
         try {
             String rez = new String(Base64.encodeBase64(text.getBytes("UTF-8")));
             return rez;
         } catch (UnsupportedEncodingException e) {
             return null;
         }
     }
convertToHex()
static String convertToHex (byte[] data) static private
{
         StringBuffer buf = new StringBuffer();
         for (int i = 0; i < data.length; i++) {
             int halfbyte = (data[i] >>> 4) & 0x0F;
             int two_halfs = 0;
             do {
                 if ((0 <= halfbyte) && (halfbyte <= 9)) {
                     buf.append((char) ('0' + halfbyte));
                 } else {
                     buf.append((char) ('a' + (halfbyte - 10)));
                 }
                 halfbyte = data[i] & 0x0F;
             } while (two_halfs++ < 1);
         }
         return buf.toString();
     }
Referenced by Crypt.SHA1().
generateHash()
static String generateHash () throws NoSuchAlgorithmException, UnsupportedEncodingException static
{
         UUID newUUID = UUID.randomUUID();
         String pwd = MD5(newUUID.toString());
         pwd = pwd.substring(0, 25);
         return pwd;
     }
References Crypt.MD5().
Referenced by AuthResource.getHash(), and SQlite.insertUser().
MD5()
static String MD5 (String text) throws NoSuchAlgorithmException, UnsupportedEncodingException static
{
         MessageDigest md;
         md = MessageDigest.getInstance("MD5");
         md.update(text.getBytes());
         byte byteData[] = md.digest();
         StringBuffer sb = new StringBuffer();
         for (int i = 0; i < byteData.length; i++) {
             sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
         }
         return sb.toString();
     }
Referenced by Crypt.generateHash().
SHA1()
static String SHA1 (String text) throws NoSuchAlgorithmException, UnsupportedEncodingException static
{
         MessageDigest md;
         md = MessageDigest.getInstance("SHA-1");
         byte[] sha1hash = new byte[40];
         md.update(text.getBytes("iso-8859-1"), 0, text.length());
         sha1hash = md.digest();
         return convertToHex(sha1hash);
     }
References Crypt.convertToHex().
Referenced by AuthResource.getHash(), SQlite.getUserInfoAndCheckPassword(), and SQlite.insertUser().