labelingsystem-server: ConfigProperties Class Reference
ConfigProperties Class Reference
Static Public Member Functions
static String getPropertyParam (String param) throws IOException
Static Private Member Functions
static boolean loadpropertyFile (String fileName) throws IOException
Static Private Attributes
static final Properties prop = new Properties()
static final String fileName = "configDevServer.properties"
Member Function Documentation
getPropertyParam()
static String getPropertyParam (String param) throws IOException static
{
                 loadpropertyFile(fileName);
                 return prop.getProperty(param);
         }
References ConfigProperties.fileName, ConfigProperties.loadpropertyFile(), and ConfigProperties.prop.
Referenced by SQlite.activateUser(), ImportcsvResource.csvUpload(), ImportcsvResource.csvUploadDirectResponse(), SQlite.deactivateUser(), AgentsResource.deleteAgent(), LabelsResource.deleteLabel(), SQlite.deleteRetcatEntry(), SQlite.deleteRetcatEntryForList(), SQlite.deleteStatisticsForVocabuary(), VocabsResource.deleteVocabulary(), CORSFilter.filter(), AgentsResource.getAgent(), AgentsResource.getAgent_JSON(), AgentsResource.getAgent_XML(), AgentsResource.getAgentRDF_JSONLD(), AgentsResource.getAgentRDF_JSONRDF(), AgentsResource.getAgentRDF_N3(), AgentsResource.getAgentRDF_Turtle(), AgentsResource.getAgentRDF_XML(), AgentsResource.getAgents(), RestResource.getAPIpage(), InfoResource.getAPIpage(), LabelsResource.getInheritedFromVocabList(), LabelsResource.getLabel(), LabelsResource.getLabel_BNR(), LabelsResource.getLabel_JSON(), LabelsResource.getLabel_Relations(), LabelsResource.getLabel_XML(), LabelsResource.getLabelRDF_JSONLD(), LabelsResource.getLabelRDF_JSONRDF(), LabelsResource.getLabelRDF_N3(), LabelsResource.getLabelRDF_Turtle(), LabelsResource.getLabelRDF_XML(), LabelsResource.getLabels(), DumpResource.getList(), SQlite.getLoginStatus(), SearchResource.getResultsLabelingSystem(), SQlite.getRetcatByVocabulary(), SQlite.getRetcatByVocabularyForList(), RevisionsResource.getRevision(), RevisionsResource.getRevision_JSON(), RevisionsResource.getRevision_XML(), RevisionsResource.getRevisionRDF_JSONLD(), RevisionsResource.getRevisionRDF_JSONRDF(), RevisionsResource.getRevisionRDF_N3(), RevisionsResource.getRevisionRDF_Turtle(), RevisionsResource.getRevisionRDF_XML(), RevisionsResource.getRevisions(), SparqlResource.getSPARQLresultsGET(), SparqlResource.getSPARQLresultsPOST(), SQlite.getStatisticsForVocabuary(), AutocompleteResource.getSuggestionsForAgents(), AutocompleteResource.getSuggestionsForLabels(), AutocompleteResource.getSuggestionsForLabelsFilter(), AutocompleteResource.getSuggestionsForVocabs(), SQlite.getUserInfo(), SQlite.getUserInfoAndCheckPassword(), SQlite.getUsersInfo(), VocabsResource.getVocabularies(), VocabsResource.getVocabulary(), VocabsResource.getVocabulary_JSON(), VocabsResource.getVocabulary_XML(), VocabsResource.getVocabularyRDF_JSONLD(), VocabsResource.getVocabularyRDF_JSONRDF(), VocabsResource.getVocabularyRDF_N3(), VocabsResource.getVocabularyRDF_SKOS(), VocabsResource.getVocabularyRDF_Turtle(), VocabsResource.getVocabularyRDF_XML(), RetcatResource.getWaybackLink(), Retcat_GeoNames.info(), Retcat_LabelingSystem.info(), TestsResource.initTest(), CSV.Input(), SQlite.insertRetcatString(), SQlite.insertRetcatStringForList(), SQlite.insertStatisticsForVocabuary(), SQlite.insertUser(), Transformer.label_GET(), AuthResource.loginUser(), AgentsResource.postAgent(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), Main.processRequest(), Retcat_PersonDB.query(), Retcat_GeoNames.query(), Retcat_LabelingSystem.queryAll(), Retcat_LabelingSystem.queryVocab(), RDF.RDF(), ResourceInfoResource.redirectToRetcat(), ResourceQueryResource.redirectToRetcat(), ResourceWaybackResource.redirectToWayback(), LabelsResource.revisionSPARQLUPDATE(), SQlite.setLogin(), SQlite.setLogout(), DumpResource.startDumping(), AuthResource.statusUser(), AgentsResource.updateAgent(), LabelsResource.updateLabel(), VocabsResource.updateVocabulary(), Transformer.vocabulary_GET(), Dump.writeFile(), and Transformer.writeVocabularyStatisticsToDatabase().
loadpropertyFile()
static boolean loadpropertyFile (String fileName) throws IOException static private
{
                 InputStream input = null;
                 try {
                         ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
                         input = classLoader.getResourceAsStream(fileName);
                         prop.load(input);
                         return true;
                 } catch (Exception e) {
                         throw new IOException(e.toString());
                 } finally {
                         if (input != null) {
                                 input.close();
                         }
                 }
         }
References ConfigProperties.fileName, and ConfigProperties.prop.
Referenced by ConfigProperties.getPropertyParam().
Member Data Documentation
fileName
final String fileName = "configDevServer.properties" static private
Referenced by ConfigProperties.getPropertyParam(), and ConfigProperties.loadpropertyFile().
prop
final Properties prop = new Properties() static private
Referenced by ConfigProperties.getPropertyParam(), and ConfigProperties.loadpropertyFile().