labelingsystem-server: LocalRetcatItems Class Reference
LocalRetcatItems Class Reference
Static Public Member Functions
static List< RetcatItem > getLocalCatalogue () throws IOException, ResourceNotAvailableException
Member Function Documentation
getLocalCatalogue()
static List<RetcatItem> getLocalCatalogue () throws IOException, ResourceNotAvailableException static
{
         List<RetcatItem> retcatList = new ArrayList();
         retcatList.add(RetcatItems.getRetcatItemByName("This Labeling System"));
         //retcatList.add(RetcatItems.getRetcatItemByName("labeling.link"));
         retcatList.add(RetcatItems.getRetcatItemByName("Getty AAT"));
         retcatList.add(RetcatItems.getRetcatItemByName("Getty TGN"));
         retcatList.add(RetcatItems.getRetcatItemByName("Getty ULAN"));
         retcatList.add(RetcatItems.getRetcatItemByName("Heritage Data Historic England"));
         retcatList.add(RetcatItems.getRetcatItemByName("Heritage Data RCAHMS"));
         retcatList.add(RetcatItems.getRetcatItemByName("Heritage Data RCAHMW"));
         retcatList.add(RetcatItems.getRetcatItemByName("ChronOntology"));
         return retcatList;
     }
Referenced by LabelsResource.getLabel(), LabelsResource.getLabel_JSON(), LabelsResource.getLabels(), RetcatResource.getRetcatDetails(), RetcatResource.getRetcatGroups(), RetcatResource.getRetcatList(), RetcatResource.getRetcatListByVocabulary(), RetcatResource.getRetcatQualities(), RetcatResource.getRetcatTypes(), RetcatResource.getWaybackLink(), Retcat_BGSLinkedData.info(), Retcat_Dbpedia.info(), Retcat_PersonDB.info(), Retcat_Pleiades.info(), Retcat_GeoNames.info(), Retcat_ChronOntology.info(), Retcat_Finto.info(), Retcat_Wikidata.info(), Retcat_Fao.info(), Retcat_Unesco.info(), Retcat_Archwort.info(), Retcat_LabelingSystem.info(), Retcat_Getty.info(), Retcat_HeritageData.info(), LabelsResource.postLabel(), Retcat_Pleiades.query(), Retcat_Finto.query(), Retcat_Unesco.query(), Retcat_ChronOntology.query(), Retcat_Dbpedia.query(), Retcat_Fao.query(), Retcat_PersonDB.query(), Retcat_Archwort.query(), Retcat_Wikidata.query(), Retcat_GeoNames.query(), Retcat_Getty.queryAAT(), Retcat_LabelingSystem.queryAll(), Retcat_HeritageData.queryHE(), Retcat_HeritageData.queryRCAHMS(), Retcat_HeritageData.queryRCAHMW(), Retcat_Getty.queryTGN(), Retcat_Getty.queryULAN(), Retcat_LabelingSystem.queryVocab(), ResourceInfoResource.redirectToRetcat(), ResourceQueryResource.redirectToRetcat(), RetcatResource.setRetcatForVocabulary(), LabelsResource.updateLabel(), and RetcatResource.updateRetcatForVocabulary().