labelingsystem-server: Similarity Class Reference
Similarity Class Reference
A library implementing different string similarity and distance measures.
Static Public Member Functions
static double Levenshtein (String s1, String s2)
static double NormalizedLevenshtein (String s1, String s2)
static double WeightedLevenshtein (String s1, String s2)
static double Damerau (String s1, String s2)
static double JaroWinkler (String s1, String s2)
static double LongestCommonSubsequence (String s1, String s2)
static double MetricLCS (String s1, String s2)
static double twoGram (String s1, String s2)
static double NGram (String s1, String s2)
static double QGram (String s1, String s2)
Detailed Description
A library implementing different string similarity and distance measures.
A dozen of algorithms (including Levenshtein edit distance and sibblings, Jaro-Winkler, Longest Common Subsequence, cosine similarity etc.) are currently implemented. Check the summary table below for the complete list... https://github.com/tdebatty/java-string-similarity
Author
Copyright 2015 Thibault Debatty https://github.com/tdebatty/java-string-similarity/blob/master/LICENSE.md
Member Function Documentation
Damerau()
static double Damerau (String s1, String s2) static
{
                 Damerau d = new Damerau();
                 return d.distance(s1, s2);
         }
JaroWinkler()
static double JaroWinkler (String s1, String s2) static
{
                 JaroWinkler jw = new JaroWinkler();
                 return jw.similarity(s1, s2);
         }
Levenshtein()
static double Levenshtein (String s1, String s2) static
{
                 Levenshtein l = new Levenshtein();
                 return l.distance(s1, s2);
         }
LongestCommonSubsequence()
static double LongestCommonSubsequence (String s1, String s2) static
{
                 LongestCommonSubsequence lcs = new LongestCommonSubsequence();
                 return lcs.distance(s1, s2);
         }
MetricLCS()
static double MetricLCS (String s1, String s2) static
{
                 MetricLCS lcs = new MetricLCS();
                 return lcs.distance(s1, s2);
         }
NGram()
static double NGram (String s1, String s2) static
Referenced by Similarity.twoGram().
{
                 NGram ngram = new NGram(4);
                 return ngram.distance(s1, s2);
         }
NormalizedLevenshtein()
static double NormalizedLevenshtein (String s1, String s2) static
Referenced by SearchResource.getResultsLabelingSystem().
{
                 NormalizedLevenshtein nl = new NormalizedLevenshtein();
                 return nl.distance(s1, s2);
         }
QGram()
static double QGram (String s1, String s2) static
{
                 QGram dig = new QGram(2);
                 return dig.distance(s1, s2);
         }
twoGram()
static double twoGram (String s1, String s2) static
References Similarity.NGram().
{
                 NGram twogram = new NGram(2);
                 return twogram.distance(s1, s2);
         }
WeightedLevenshtein()
static double WeightedLevenshtein (String s1, String s2) static
{
                 WeightedLevenshtein wl = new WeightedLevenshtein(
                                 new CharacterSubstitutionInterface() {
                         public double cost(char c1, char c2) {
                                 // The cost for substituting 't' and 'r' is considered
                                 // smaller as these 2 are located next to each other
                                 // on a keyboard
                                 if (c1 == 't' && c2 == 'r') {
                                         return 0.5;
                                 }
                                 // For most cases, the cost of substituting 2 characters
                                 // is 1.0
                                 return 1.0;
                         }
                 });
                 return wl.distance(s1, s2);
         }