labelingsystem-server: GeneralFunctions Class Reference
GeneralFunctions Class Reference
Static Public Member Functions
static String getAllElementsForItemID (String item, String itemid) throws ConfigException, IOException
static String getAllLabelsForVocabulary (String itemid) throws ConfigException, IOException
static String getSPARQLqueryElementsForRetcatsItem (String itemid) throws ConfigException, IOException
static String getHierarchyForLabelsOneStep (String itemid) throws ConfigException, IOException
static String getRelationsForLabelsByCreator (String itemid) throws ConfigException, IOException
static String encodeURIComponent (String s)
static String encodeURIUmlaut (String s)
Member Function Documentation
encodeURIComponent()
static String encodeURIComponent (String s) static
{
         String result;
         try {
             result = URLEncoder.encode(s, "UTF-8")
                     .replaceAll("\\+", "%20")
                     .replaceAll("\\%21", "!")
                     .replaceAll("\\%27", "'")
                     .replaceAll("\\%28", "(")
                     .replaceAll("\\%29", ")")
                     .replaceAll("\\%7E", "~");
         } catch (UnsupportedEncodingException e) {
             result = s;
         }
         return result;
     }
Referenced by Retcat_Pleiades.info(), Retcat_Finto.info(), Retcat_Fao.info(), Retcat_Unesco.info(), Retcat_Pleiades.query(), Retcat_Finto.query(), Retcat_ChronOntology.query(), Retcat_Dbpedia.query(), Retcat_Unesco.query(), Retcat_Fao.query(), Retcat_PersonDB.query(), Retcat_GeoNames.query(), and ResourceQueryResource.redirectToRetcat().
encodeURIUmlaut()
static String encodeURIUmlaut (String s) static
{
         s = s.replaceAll("Ä", "%C3%84").replaceAll("ä", "%C3%A4");
                 return s;
     }
Referenced by Retcat_HTML.info(), and Retcat_HTML.query().
getAllElementsForItemID()
static String getAllElementsForItemID (String item, String itemid) throws ConfigException, IOException static
{
         RDF rdf = new RDF();
         String prefixes = rdf.getPREFIXSPARQL();
         String query = prefixes + "SELECT * WHERE { ";
         query += item + ":" + itemid + " ?p ?o. } ";
         query += "ORDER BY ASC(?p)";
         return query;
     }
Referenced by AgentsResource.deleteAgent(), LabelsResource.deleteLabel(), VocabsResource.deleteVocabulary(), AgentsResource.getAgent(), AgentsResource.getAgent_JSON(), AgentsResource.getAgent_XML(), AgentsResource.getAgentRDF_JSONLD(), AgentsResource.getAgentRDF_JSONRDF(), AgentsResource.getAgentRDF_N3(), AgentsResource.getAgentRDF_Turtle(), AgentsResource.getAgentRDF_XML(), LabelsResource.getLabel(), LabelsResource.getLabel_JSON(), LabelsResource.getLabel_XML(), LabelsResource.getLabelRDF_JSONLD(), LabelsResource.getLabelRDF_JSONRDF(), LabelsResource.getLabelRDF_N3(), LabelsResource.getLabelRDF_Turtle(), LabelsResource.getLabelRDF_XML(), RevisionsResource.getRevision(), RevisionsResource.getRevision_JSON(), RevisionsResource.getRevision_XML(), RevisionsResource.getRevisionRDF_JSONLD(), RevisionsResource.getRevisionRDF_JSONRDF(), RevisionsResource.getRevisionRDF_N3(), RevisionsResource.getRevisionRDF_Turtle(), RevisionsResource.getRevisionRDF_XML(), VocabsResource.getVocabulary(), VocabsResource.getVocabulary_JSON(), VocabsResource.getVocabulary_XML(), VocabsResource.getVocabularyRDF_JSONLD(), VocabsResource.getVocabularyRDF_JSONRDF(), VocabsResource.getVocabularyRDF_N3(), VocabsResource.getVocabularyRDF_SKOS(), VocabsResource.getVocabularyRDF_Turtle(), VocabsResource.getVocabularyRDF_XML(), AuthResource.loginUser(), AgentsResource.postAgent(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), AuthResource.statusUser(), AgentsResource.updateAgent(), LabelsResource.updateLabel(), and VocabsResource.updateVocabulary().
getAllLabelsForVocabulary()
static String getAllLabelsForVocabulary (String itemid) throws ConfigException, IOException static
{
         RDF rdf = new RDF();
         String prefixes = rdf.getPREFIXSPARQL();
         String query = prefixes + "SELECT * WHERE { ";
         query += "?s skos:inScheme ?voc . ";
         query += "?s dc:identifier ?id . ";
         query += "FILTER (?voc=ls_voc:" + itemid + ") }";
         return query;
     }
Referenced by VocabsResource.deleteVocabulary(), and VocabsResource.getVocabularyRDF_SKOS().
getHierarchyForLabelsOneStep()
static String getHierarchyForLabelsOneStep (String itemid) throws ConfigException, IOException static
{
         RDF rdf = new RDF();
         String prefixes = rdf.getPREFIXSPARQL();
         String query = prefixes + "SELECT ?narrowerTerm ?broaderTerm ?relatedTerm WHERE { ";
         query += "?s a ls:Label. ";
         query += "?s dc:identifier ?identifier. ";
         query += "OPTIONAL { ?s skos:narrower ?narrower. ?narrower ls:thumbnail ?narrowerTerm. }";
         query += "OPTIONAL { ?s skos:broader ?broader. ?broader ls:thumbnail ?broaderTerm. }";
         query += "OPTIONAL { ?s skos:related ?related. ?related ls:thumbnail ?relatedTerm. }";
         query += "FILTER (?identifier=\"$identifier\") }";
         query = query.replace("$identifier", itemid);
         return query;
     }
Referenced by LabelsResource.getLabel_BNR().
getRelationsForLabelsByCreator()
static String getRelationsForLabelsByCreator (String itemid) throws ConfigException, IOException static
{
         RDF rdf = new RDF();
         String prefixes = rdf.getPREFIXSPARQL();
         String query = prefixes + "SELECT ?nt ?bt ?rt ?nmt ?bmt ?rmt ?cmt ?emt WHERE { ";
         query += "?label a ls:Label. ";
         query += "?label dc:identifier ?identifier. ";
         query += "?label dc:creator ?creator. ";
         query += "OPTIONAL { ?narrower skos:narrower ?label. ?narrower dc:creator ?creator. ?narrower ls:thumbnail ?nt. }";
         query += "OPTIONAL { ?broader skos:broader ?label. ?broader dc:creator ?broader. ?narrower ls:thumbnail ?bt. }";
         query += "OPTIONAL { ?related skos:related ?label. ?related dc:creator ?creator. ?related ls:thumbnail ?rt. }";
         query += "OPTIONAL { ?narrowMatch skos:narrowMatch ?label. ?narrowMatch dc:creator ?creator. ?narrowMatch ls:thumbnail ?nmt. }";
         query += "OPTIONAL { ?broadMatch skos:broadMatch ?label. ?broadMatch dc:creator ?creator. ?broadMatch ls:thumbnail ?bmt. }";
         query += "OPTIONAL { ?relatedMatch skos:relatedMatch ?label. ?relatedMatch dc:creator ?creator. ?relatedMatch ls:thumbnail ?rmt. }";
         query += "OPTIONAL { ?closeMatch skos:closeMatch ?label. ?closeMatch dc:creator ?creator. ?closeMatch ls:thumbnail ?cmt. }";
         query += "OPTIONAL { ?exactMatch skos:exactMatch ?label. ?exactMatch dc:creator ?creator. ?exactMatch ls:thumbnail ?emt. }";
         query += "FILTER (?identifier=\"$identifier\") }";
         query = query.replace("$identifier", itemid);
         return query;
     }
Referenced by LabelsResource.getLabel_Relations().
getSPARQLqueryElementsForRetcatsItem()
static String getSPARQLqueryElementsForRetcatsItem (String itemid) throws ConfigException, IOException static
{
         RDF rdf = new RDF();
         String prefixes = rdf.getPREFIXSPARQL();
         String query = prefixes + "SELECT ?var ?query ?url WHERE { ";
         query += "?retcat dc:identifier ?identifier. ";
         query += "?retcat ls:retcatsquery ?query. ";
         query += "?retcat ls:retcatsvar ?var. ";
         query += "?retcat dcat:accessURL ?url. ";
         query += "FILTER (?identifier=\"$identifier\") }";
         query = query.replace("$identifier", itemid);
         return query;
     }