labelingsystem-server: UniqueIdentifier Class Reference
UniqueIdentifier Class Reference
Static Public Member Functions
static String getHashID ()
static String getUniversallyUniqueIdentifier2 ()
Member Function Documentation
getHashID()
static String getHashID () static
{
                 // https://github.com/jiecao-fm/hashids-java
                 Hashids hashids = new Hashids(getUniversallyUniqueIdentifier2(), 12);
                 String hash = hashids.encode(1234567L);
                 return hash;
         }
References UniqueIdentifier.getUniversallyUniqueIdentifier2().
Referenced by CSV.createLabelTriples(), AuthResource.loginUser(), LabelsResource.postLabel(), VocabsResource.postVocabulary(), and LabelsResource.revisionSPARQLUPDATE().
getUniversallyUniqueIdentifier2()
static String getUniversallyUniqueIdentifier2 () static
{
                 UUID newUUID = UUID.randomUUID();
                 return newUUID.toString();
         }
Referenced by UniqueIdentifier.getHashID().