labelingsystem-server: Logging Class Reference
Logging Class Reference
CLASS for show errormessages.
Static Public Member Functions
static String getMessageXML (Exception exception, String endClass) throws ParserConfigurationException, TransformerException
XML ERROR MESSAGE for catch exceptions.
static String getMessageJSON (Exception exception, String endClass)
JSON ERROR MESSAGE for catch exceptions.
static String getMessageTEXT (Exception exception, String endClass)
TEXT ERROR MESSAGE for catch exceptions.
Detailed Description
CLASS for show errormessages.
Author
Florian Thiery M.Sc.
Member Function Documentation
getMessageJSON()
static String getMessageJSON (Exception exception, String endClass) static
JSON ERROR MESSAGE for catch exceptions.
Parameters
exception this exception
endClass class path where exception tree ends
Returns
error message JSON
{
                 // START BUILD JSON
                 Gson gson = new GsonBuilder().setPrettyPrinting().create();
                 JSONObject jsonobj_error = new JSONObject(); // {}
                 JSONObject jsonobj_error_data = new JSONObject(); // {}
                 JSONArray jsonarray_element = new JSONArray();
                 for (StackTraceElement element : exception.getStackTrace()) {
                         jsonarray_element.add(element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber());
                         if (element.getClassName().equals(endClass)) {
                                 break;
                         }
                 }
                 jsonobj_error.put("error", jsonobj_error_data);
                 jsonobj_error_data.put("message", exception.toString());
                 jsonobj_error_data.put("description", jsonarray_element);
                 // OUTPUT AS pretty print JSON
                 return gson.toJson(jsonobj_error);
         }
Referenced by GenericResource.getAgent(), GenericResource.getConcept(), GenericResource.getLabel(), GenericResource.getRevision(), GenericResource.getVocab(), and GenericResource.getVocabulary().
getMessageTEXT()
static String getMessageTEXT (Exception exception, String endClass) static
TEXT ERROR MESSAGE for catch exceptions.
Parameters
exception this exception
endClass class path where exception tree ends
Returns
error message TEXT
{
                 String message = "error\n";
                 message += "message: \"" + exception.toString() + "\"";
                 for (StackTraceElement element : exception.getStackTrace()) {
                         message += "\ndescription: \"" + element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber() + "\"";
                         if (element.getClassName().equals(endClass)) {
                                 break;
                         }
                 }
                 return message;
         }
getMessageXML()
static String getMessageXML (Exception exception, String endClass) throws ParserConfigurationException, TransformerException static
XML ERROR MESSAGE for catch exceptions.
Parameters
exception this exception
endClass class path where exception tree ends
Returns
error message XML
Exceptions
javax.xml.parsers.ParserConfigurationException
javax.xml.transform.TransformerException
{
                 XMLBuilder xml = XMLBuilder.create("error")
                                 .e("message")
                                 .t(exception.toString())
                                 .up();
                 for (StackTraceElement element : exception.getStackTrace()) {
                         xml.e("description")
                                         .t(element.getClassName() + " / " + element.getMethodName() + "() / " + element.getLineNumber())
                                         .up();
                         if (element.getClassName().equals(endClass)) {
                                 break;
                         }
                 }
                 return xml.asString();
         }