labelingsystem-server: ConfigProperties Class Reference
ConfigProperties Class Reference
CLASS for property file actions.
Static Public Member Functions
static String getPropertyParam (String param) throws IOException
get parameter of property file
Static Private Member Functions
static boolean loadpropertyFile (String fileName) throws IOException
load property file
Static Private Attributes
static final Properties prop = new Properties()
static final String fileName = "config.properties"
Detailed Description
CLASS for property file actions.
Author
Florian Thiery M.Sc.
Member Function Documentation
getPropertyParam()
static String getPropertyParam (String param) throws IOException static
get parameter of property file
Parameters
param param name in the properties file
Returns
param value
Exceptions
IOException
References ConfigProperties.loadpropertyFile().
Referenced by GenericResource.getAgent(), GenericResource.getConcept(), GenericResource.getLabel(), GenericResource.getRevision(), GenericResource.getVocab(), and GenericResource.getVocabulary().
{
                 loadpropertyFile(fileName);
                 return prop.getProperty(param);
         }
loadpropertyFile()
static boolean loadpropertyFile (String fileName) throws IOException static private
load property file
Parameters
fileName name of the properties file
Returns
loaded or not
Exceptions
IOException
Referenced by ConfigProperties.getPropertyParam().
{
                 InputStream input = null;
                 try {
                         ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
                         input = classLoader.getResourceAsStream(fileName);
                         prop.load(input);
                         return true;
                 } catch (Exception e) {
                         throw new IOException(e.toString());
                 } finally {
                         if (input != null) {
                                 input.close();
                         }
                 }
         }
Member Data Documentation
fileName
final String fileName = "config.properties" static private
prop
final Properties prop = new Properties() static private