var hierarchy =
[
    [ "AgentsResource", "a00391.html", null ],
    [ "AuthResource", "a00395.html", null ],
    [ "AutocompleteResource", "a00399.html", null ],
    [ "ConfigProperties", "a00611.html", null ],
    [ "ConfigProperties", "a00487.html", null ],
    [ "Crypt", "a00491.html", null ],
    [ "Dump", "a00503.html", null ],
    [ "DumpResource", "a00403.html", null ],
    [ "Exception", "a01155.html", [
      [ "AccessDeniedException", "a00283.html", null ],
      [ "AutocompleteLengthException", "a00287.html", null ],
      [ "ConfigException", "a00291.html", null ],
      [ "CsvExistanceException", "a00295.html", null ],
      [ "CsvLabelImportException", "a00299.html", null ],
      [ "CsvLanguageException", "a00303.html", null ],
      [ "FormatException", "a00307.html", null ],
      [ "JsonFormatException", "a00311.html", null ],
      [ "MemoryException", "a00319.html", null ],
      [ "NoInputException", "a00323.html", null ],
      [ "RdfException", "a00327.html", null ],
      [ "ResourceNotAvailableException", "a00331.html", null ],
      [ "RetcatException", "a00335.html", null ],
      [ "RevisionTypeException", "a00339.html", null ],
      [ "SesameSparqlException", "a00343.html", null ],
      [ "SparqlParseException", "a00347.html", null ],
      [ "SparqlQueryException", "a00351.html", null ],
      [ "SparqlUpdateException", "a00355.html", null ],
      [ "SQliteException", "a00359.html", null ],
      [ "StatisticsException", "a00363.html", null ],
      [ "TransformRdfToApiJsonException", "a00367.html", null ],
      [ "UniqueIdentifierException", "a00371.html", null ],
      [ "ValidateJSONObjectException", "a00375.html", null ],
      [ "WaybacklinkException", "a00379.html", null ]
    ] ],
    [ "GeneralFunctions", "a00511.html", null ],
    [ "GenericResource", "a00619.html", null ],
    [ "Gzip", "a00475.html", null ],
    [ "ImportcsvResource", "a00407.html", null ],
    [ "InfoResource", "a00411.html", null ],
    [ "InheritFromVocab", "a00515.html", null ],
    [ "LabelsResource", "a00415.html", null ],
    [ "LanguagesResource", "a00419.html", null ],
    [ "LicensesResource", "a00423.html", null ],
    [ "LocalRetcatItems", "a00519.html", null ],
    [ "Logging", "a00315.html", null ],
    [ "Logging", "a00607.html", null ],
    [ "PATCH", "a00483.html", null ],
    [ "RDF", "a00383.html", null ],
    [ "ResourceInfoResource", "a00427.html", null ],
    [ "ResourceQueryResource", "a00431.html", null ],
    [ "ResourceWaybackResource", "a00435.html", null ],
    [ "RestResource", "a00439.html", null ],
    [ "Retcat_Archwort", "a00523.html", null ],
    [ "Retcat_BGSLinkedData", "a00527.html", null ],
    [ "Retcat_ChronOntology", "a00531.html", null ],
    [ "Retcat_Dbpedia", "a00535.html", null ],
    [ "Retcat_Fao", "a00539.html", null ],
    [ "Retcat_Finto", "a00543.html", null ],
    [ "Retcat_GeoNames", "a00547.html", null ],
    [ "Retcat_Getty", "a00551.html", null ],
    [ "Retcat_HeritageData", "a00555.html", null ],
    [ "Retcat_HTML", "a00559.html", null ],
    [ "Retcat_LabelingSystem", "a00563.html", null ],
    [ "Retcat_PersonDB", "a00567.html", null ],
    [ "Retcat_Pleiades", "a00571.html", null ],
    [ "Retcat_Unesco", "a00575.html", null ],
    [ "Retcat_Wikidata", "a00579.html", null ],
    [ "RetcatResource", "a00443.html", null ],
    [ "RevisionsResource", "a00447.html", null ],
    [ "Runnable", "a01159.html", [
      [ "CSV", "a00495.html", null ],
      [ "LSDump", "a00507.html", null ]
    ] ],
    [ "SearchResource", "a00455.html", null ],
    [ "Similarity", "a00583.html", null ],
    [ "SparqlResource", "a00459.html", null ],
    [ "SQlite", "a00499.html", null ],
    [ "TarGZ", "a00599.html", null ],
    [ "TestsResource", "a00463.html", null ],
    [ "TestTransformer", "a00603.html", null ],
    [ "Transformer", "a00587.html", null ],
    [ "UniqueIdentifier", "a00591.html", null ],
    [ "ValidateJSONObject", "a00595.html", null ],
    [ "VocabsResource", "a00467.html", null ],
    [ "ContainerResponseFilter", null, [
      [ "CORSFilter", "a00615.html", null ],
      [ "CORSFilter", "a00471.html", null ]
    ] ],
    [ "HttpServlet", null, [
      [ "Main", "a00387.html", null ]
    ] ],
    [ "RetcatREST", null, [
      [ "RtcResource", "a00451.html", null ]
    ] ],
    [ "WriterInterceptor", null, [
      [ "GZIPWriterInterceptor", "a00479.html", null ]
    ] ]
];